// Dev-only. Run: pnpm exec tsx packages/core/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_core_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'core';

// Tables with an updated_at column that must be bumped on every UPDATE.
const TOUCH_TABLES = ['skill', 'skill_category', 'subscription_failure_state'];

// Tenant-scoped tables that get the RLS backstop policy (spec §3.1).
const RLS_TABLES = ['skill', 'skill_category', 'session_scope_cache'];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
