-- drizzle cannot model: extensions, trigram GIN indexes, touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ../generate-platform-sql.ts.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Trigram GIN indexes backing worker directory search (Drizzle cannot model gin_trgm_ops).
CREATE INDEX IF NOT EXISTS worker_full_name_trgm ON people.worker USING gin (full_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS worker_work_email_trgm ON people.worker USING gin (work_email gin_trgm_ops);
CREATE INDEX IF NOT EXISTS worker_job_title_trgm ON people.worker USING gin (job_title gin_trgm_ops);

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION people.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER person_touch_updated_at
BEFORE UPDATE ON people.person
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER employment_period_touch_updated_at
BEFORE UPDATE ON people.employment_period
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER worker_touch_updated_at
BEFORE UPDATE ON people.worker
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER org_unit_touch_updated_at
BEFORE UPDATE ON people.org_unit
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER person_skill_touch_updated_at
BEFORE UPDATE ON people.person_skill
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER worker_allocation_projection_touch_updated_at
BEFORE UPDATE ON people.worker_allocation_projection
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER account_projection_touch_updated_at
BEFORE UPDATE ON people.account_projection
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();
CREATE TRIGGER project_projection_touch_updated_at
BEFORE UPDATE ON people.project_projection
FOR EACH ROW EXECUTE FUNCTION people.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE people.person ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.person FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.person
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.employment_period ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.employment_period FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.employment_period
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.worker ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.worker FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.worker
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.org_unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.org_unit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.org_unit
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.person_skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.person_skill FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.person_skill
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.worker_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.worker_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.worker_history
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.worker_allocation_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.worker_allocation_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.worker_allocation_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.account_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.account_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.account_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE people.project_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE people.project_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON people.project_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA people TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA people TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA people GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
