/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/astryx-seta.theme.ts
 * Command: astryx theme build src/theme/astryx-seta.theme.ts --out src/styles/astryx-seta-theme.css
 * Generated: 2026-07-13T05:22:20.104Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const setaTheme: DefinedTheme;
