#!/usr/bin/env bash
# Render the runtime env file for a compose deploy from the process environment.
# The deploy workflow injects GitHub Environment Variables + Secrets as env vars;
# this writes the subset compose.yaml consumes. Values are never echoed.
set -euo pipefail

OUT="${1:?usage: render-env.sh <output-path>}"
umask 077
: > "$OUT"

emit() {  # emit KEY — write KEY=value if the value is non-empty
  local key="$1" val="${!1:-}"
  if [ -n "$val" ]; then printf '%s=%s\n' "$key" "$val" >> "$OUT"; fi
}

for key in \
  NODE_ENV PORT PLATFORM_MODULES PLATFORM_VERSION \
  DATABASE_URL DATABASE_APP_URL PUBLIC_URL BETTER_AUTH_SECRET \
  CORS_ORIGINS SESSION_COOKIE_SAMESITE EVENTS_RETENTION_DAYS \
  CRYPTO_KEY_PROVIDER CRYPTO_LOCAL_MASTER_KEY AWS_REGION \
  POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_BIND_ADDR \
  HTTP_BIND HTTPS_BIND SMOKE_BIND \
  PLATFORM_DOMAIN PLATFORM_TLS_MODE PLATFORM_ACME_EMAIL \
  S3_REGION S3_ENDPOINT S3_BUCKET S3_FORCE_PATH_STYLE \
  S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY \
  OPENAI_API_KEY AGENT_MODELS AGENT_MODEL_DEFAULT EMBED_MODEL \
  OLLAMA_BASE_URL OLLAMA_API_KEY VLLM_BASE_URL VLLM_API_KEY \
  LLAMACPP_BASE_URL LLAMACPP_API_KEY \
  MICROSOFT_CLIENT_ID MICROSOFT_CLIENT_SECRET M365_WEBHOOK_SECRET \
  M365_GRAPH_TENANT_ID M365_GRAPH_CLIENT_ID M365_GRAPH_CLIENT_SECRET \
  MAILER_DEFAULT_TRANSPORT MAILER_DEFAULT_SENDER MAILER_DEFAULT_SENDER_DISPLAY_NAME \
  MAILER_DEFAULT_SMTP_URL MAILER_GRAPH_CLIENT_ID MAILER_GRAPH_CLIENT_SECRET \
  ECR_REGISTRY ECR_REPOSITORY \
  MONITORING_ENV REMOTE_WRITE_URL LOKI_URL REMOTE_WRITE_USERNAME REMOTE_WRITE_PASSWORD \
  CLOUDWATCH_TARGET DCGM_TARGET CADVISOR_TARGET POSTGRES_EXPORTER_DSN \
; do emit "$key"; done

echo "rendered $(grep -c '=' "$OUT") keys to $OUT"
