-- drizzle cannot model: deferrable FKs, touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ./generate-platform-sql.ts.

-- Drizzle cannot model DEFERRABLE foreign keys. The workflow_run_events_seen dedup row is
-- inserted as the idempotency gate BEFORE its workflow_runs parent exists (the run row is
-- created later in the same run-started transaction), so the FK must be validated at COMMIT
-- rather than per-statement.
ALTER TABLE "agent"."workflow_run_events_seen"
  ALTER CONSTRAINT "workflow_run_events_seen_run_id_workflow_runs_run_id_fk"
  DEFERRABLE INITIALLY DEFERRED;

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION agent.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER tenant_settings_touch_updated_at
BEFORE UPDATE ON agent.tenant_settings
FOR EACH ROW EXECUTE FUNCTION agent.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE agent.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.rate_limits FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.rate_limits
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE agent.tenant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.tenant_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.tenant_settings
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE agent.workflow_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.workflow_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.workflow_runs
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE agent.workflow_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.workflow_approvals FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.workflow_approvals
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE agent.workflow_run_events_seen ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.workflow_run_events_seen FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.workflow_run_events_seen
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE agent.workflow_run_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.workflow_run_steps FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.workflow_run_steps
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
-- The ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER clause covers the mastra_* tables that
-- Mastra's PostgresStore creates in this schema at runtime: they are created by the same DB
-- role that runs migrations (both use DATABASE_URL — the migrator/worker/mastraState connection),
-- so future tables it owns automatically grant to seta_app without a follow-up migration.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA agent TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA agent TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA agent GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER IN SCHEMA agent GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
