// Dev-only. Run: pnpm exec tsx packages/agent/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_agent_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'agent';

// Agent tables with an updated_at column. Only tenant_settings is mutated in place;
// the workflow_* rows are lifecycle-transitioned via explicit column writes, and
// rate_limits is an append/upsert counter — none carry updated_at.
const TOUCH_TABLES = ['tenant_settings'];

// Every agent-owned domain table is tenant-scoped (all carry tenant_id) and gets the RLS
// backstop policy (constitution: none allowlisted). The runtime-created mastra_* tables are
// NOT covered here — they are census-allowlisted in Task 10 (Mastra owns their DDL; they are
// scoped at the app layer by the tenant-guarded store, not by a tenant_id column).
const RLS_TABLES = [
  'rate_limits',
  'tenant_settings',
  'workflow_runs',
  'workflow_approvals',
  'workflow_run_events_seen',
  'workflow_run_steps',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
