-- drizzle cannot model: extensions, trigram GIN indexes, touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ../generate-platform-sql.ts.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Trigram GIN index backing candidate name search (Drizzle cannot model gin_trgm_ops).
CREATE INDEX IF NOT EXISTS candidate_name_trgm ON hiring.candidate USING gin (name gin_trgm_ops);

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION hiring.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER requisition_touch_updated_at
BEFORE UPDATE ON hiring.requisition
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER opening_touch_updated_at
BEFORE UPDATE ON hiring.opening
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER requisition_jd_section_touch_updated_at
BEFORE UPDATE ON hiring.requisition_jd_section
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER requisition_skill_touch_updated_at
BEFORE UPDATE ON hiring.requisition_skill
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER opening_close_reason_touch_updated_at
BEFORE UPDATE ON hiring.opening_close_reason
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER jd_template_touch_updated_at
BEFORE UPDATE ON hiring.jd_template
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER jd_template_section_touch_updated_at
BEFORE UPDATE ON hiring.jd_template_section
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER candidate_touch_updated_at
BEFORE UPDATE ON hiring.candidate
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER candidate_skill_touch_updated_at
BEFORE UPDATE ON hiring.candidate_skill
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER rejection_reason_touch_updated_at
BEFORE UPDATE ON hiring.rejection_reason
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();
CREATE TRIGGER application_touch_updated_at
BEFORE UPDATE ON hiring.application
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE hiring.requisition ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.requisition FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.requisition
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.opening ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.opening FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.opening
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.requisition_jd_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.requisition_jd_section FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.requisition_jd_section
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.requisition_skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.requisition_skill FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.requisition_skill
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.opening_close_reason ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.opening_close_reason FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.opening_close_reason
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.jd_template ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.jd_template FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.jd_template
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.jd_template_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.jd_template_section FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.jd_template_section
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.candidate ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.candidate FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.candidate
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.candidate_skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.candidate_skill FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.candidate_skill
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.rejection_reason ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.rejection_reason FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.rejection_reason
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.candidate_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.candidate_event FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.candidate_event
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.application ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.application FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.application
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA hiring TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hiring TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA hiring GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
