-- drizzle cannot model: RLS policies. Verbatim output of ../generate-platform-sql.ts's
-- buildRlsSql for the FUT-326/327 projection tables added in 0002_round_blacklash.sql.

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE hiring.account_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.account_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.account_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.project_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.project_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.project_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.worker_user_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.worker_user_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.worker_user_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
