-- drizzle cannot model: RLS policies. Verbatim output of ../generate-platform-sql.ts's
-- buildRlsSql for hiring.project_owner_projection (FUT-328), added in
-- 0004_hiring_project_owner_projection.sql.

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE hiring.project_owner_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.project_owner_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.project_owner_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
