-- drizzle cannot model: touch triggers, RLS policies. Verbatim output of
-- ../generate-platform-sql.ts's buildTouchTriggerSql/buildRlsSql for the hiring.reason table
-- added in 0010_gorgeous_nico_minoru.sql.

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE TRIGGER reason_touch_updated_at
BEFORE UPDATE ON hiring.reason
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE hiring.reason ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.reason FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.reason
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
