-- drizzle cannot model: touch triggers, RLS policies. Verbatim output of
-- ../generate-platform-sql.ts's buildTouchTriggerSql/buildRlsSql for the hiring.interview /
-- hiring.interview_panelist tables added in 0019_interview_lifecycle.sql.

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE TRIGGER interview_touch_updated_at
BEFORE UPDATE ON hiring.interview
FOR EACH ROW EXECUTE FUNCTION hiring.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE hiring.interview ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.interview FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.interview
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE hiring.interview_panelist ENABLE ROW LEVEL SECURITY;
ALTER TABLE hiring.interview_panelist FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON hiring.interview_panelist
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
