-- drizzle cannot model: LIST-partitioned tables, composite FKs from a partitioned table,
-- partial indexes on non-modeled tables, touch triggers, RLS policies, grants.
-- Sections (touch trigger, RLS) are the verbatim output of ../generate-platform-sql.ts.

-- LIST-partitioned by tenant_id. Per-tenant child partitions are provisioned lazily by
-- ensureChunksPartition (parse-knowledge-file.ts). The composite FK to files (tenant_id, id)
-- is defined on the parent and inherited by every partition (PG16). files_tenant_id_id
-- (schema.ts) is the required unique index on the referenced side.
CREATE TABLE knowledge.chunks (
  tenant_id     uuid    NOT NULL,
  file_id       uuid    NOT NULL,
  chunk_ordinal integer NOT NULL CHECK (chunk_ordinal >= 0),
  chunk_text    text    NOT NULL,
  page_hint     text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, file_id, chunk_ordinal),
  FOREIGN KEY (tenant_id, file_id) REFERENCES knowledge.files (tenant_id, id) ON DELETE CASCADE
) PARTITION BY LIST (tenant_id);

-- Partial index driving the AV-scan gate (verbatim from the pre-squash 0002).
CREATE INDEX files_scan_status
  ON knowledge.files (scan_status)
  WHERE scan_status IN ('pending','scanning','error');

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION knowledge.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER files_touch_updated_at
BEFORE UPDATE ON knowledge.files
FOR EACH ROW EXECUTE FUNCTION knowledge.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE knowledge.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.files FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON knowledge.files
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE knowledge.chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.chunks FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON knowledge.chunks
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA knowledge TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA knowledge TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
