/**
 * Band threshold grammar evaluated against a metric's single computed value (see
 * `computeMetricValue`): a plain ratio (component_1 / component_2) for 2-component metrics,
 * or component_1 directly for 1-component metrics. A few metrics whose mockup formula isn't
 * a plain numerator/denominator (Margin, Forecast Accuracy, Cost Per Story Point, Revenue
 * Per BMM) are modeled by choosing component labels that ask for the already-combined number
 * (e.g. "Margin (Revenue − Cost)" instead of separate Revenue/Cost fields) — the same trick
 * the source norm already uses for Defect Removal Efficiency.
 *
 * The type itself lives in ../../contracts.ts (FUT-595: shared with the web preview) and is
 * re-exported here so existing domain imports keep working.
 */
import type { BandCondition } from '../../contracts.ts';
import type { KPI_CATEGORIES, KPI_METRIC_TIERS } from '../db/schema.ts';

export type { BandCondition } from '../../contracts.ts';

export interface KpiNormMetricSeed {
  category: (typeof KPI_CATEGORIES)[number];
  tier: (typeof KPI_METRIC_TIERS)[number];
  name: string;
  formula_label: string;
  component_count: 1 | 2;
  component_1_label: string;
  component_2_label: string | null;
  component_1_integer: boolean;
  component_2_integer: boolean;
  component_1_min: number | null;
  component_1_max: number | null;
  is_share: boolean;
  green_band: BandCondition;
  yellow_band: BandCondition;
  red_band: BandCondition;
  insight: string;
  is_live_capable: boolean;
  sort_order: number;
}

const lte = (value: number): BandCondition => ({ op: 'lte', value });
const lt = (value: number): BandCondition => ({ op: 'lt', value });
const gte = (value: number): BandCondition => ({ op: 'gte', value });
const gt = (value: number): BandCondition => ({ op: 'gt', value });
const eq = (value: number): BandCondition => ({ op: 'eq', value });
const between = (min: number, max: number): BandCondition => ({ op: 'between', min, max });
const or = (...conditions: BandCondition[]): BandCondition => ({ op: 'or', conditions });

/**
 * KPI Norm SETA-08-SOP-001 v2.0 — 44 metrics across Q/C/D/P, transcribed from the design mockup
 * (docs/design/kpi-metrics.html, KPI Norm screen). Sort order matches the mockup's own
 * Core-then-Extended reading order per category. Methodology lens (Scrum/Kanban/Waterfall/
 * Hybrid) and Executive (EQI/TDI) sections exist in the mockup too but are out of scope for
 * this pass (see docs/feature/kpi-metrics/functional-analysis.md §9 scope note, 2026-07-14).
 */
export const KPI_NORM_METRICS: readonly KpiNormMetricSeed[] = [
  // Q — Quality (25% OHS weight) — CORE
  {
    category: 'quality',
    tier: 'core',
    name: 'Defect Leakage',
    formula_label: 'Production Defects / Total Defects',
    component_count: 2,
    component_1_label: 'Production defects',
    component_2_label: 'Total defects',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: lte(0.05),
    yellow_band: between(0.06, 0.1),
    red_band: gt(0.1),
    insight: 'Quality gate tightness — Red = QA system failure or release pressure.',
    is_live_capable: true,
    sort_order: 1,
  },
  {
    category: 'quality',
    tier: 'core',
    name: 'Internal Defect Density',
    formula_label: 'Internal Defects / BMM',
    component_count: 2,
    component_1_label: 'Internal defects',
    component_2_label: 'BMM',
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.5, 2.5),
    yellow_band: or(between(2.6, 4.0), lt(0.5)),
    red_band: gt(4.0),
    insight: '< 0.5 suggests under-reporting; > 4 = overload or skill gap.',
    is_live_capable: true,
    sort_order: 2,
  },
  {
    category: 'quality',
    tier: 'core',
    name: 'Reopened Defect Rate',
    formula_label: 'Reopened Defects / Total Defects Closed',
    component_count: 2,
    component_1_label: 'Reopened defects',
    component_2_label: 'Total defects closed',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: lte(0.05),
    yellow_band: between(0.06, 0.15),
    red_band: gt(0.15),
    insight: 'Fix quality — Red = shallow fixes, missing root cause.',
    is_live_capable: false,
    sort_order: 3,
  },
  {
    category: 'quality',
    tier: 'core',
    name: 'Defect Removal Efficiency (DRE)',
    formula_label: 'Internal Defects / (Internal + External Defects)',
    component_count: 2,
    component_1_label: 'Internal defects',
    component_2_label: 'Internal + external defects',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.95),
    yellow_band: between(0.85, 0.94),
    red_band: lt(0.85),
    insight: 'Red = customers are finding your bugs for you.',
    is_live_capable: false,
    sort_order: 4,
  },
  {
    category: 'quality',
    tier: 'core',
    name: 'Tech Health Investment (THI)',
    formula_label: 'Non-dev Effort / Total Effort',
    component_count: 2,
    component_1_label: 'Non-dev effort',
    component_2_label: 'Total effort',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: between(0.15, 0.25),
    yellow_band: or(between(0.1, 0.14), between(0.26, 0.35)),
    red_band: or(lt(0.1), gt(0.35)),
    insight: '< 10% = sacrificing architecture, will pay later; > 35% = over-investment.',
    is_live_capable: false,
    sort_order: 5,
  },
  // Q — Quality — EXTENDED
  {
    category: 'quality',
    tier: 'extended',
    name: 'MTTD — Defect',
    formula_label: 'Avg(Phase Found − Phase Injected), days',
    component_count: 1,
    component_1_label: 'Avg days (found − injected)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(3),
    yellow_band: between(4, 7),
    red_band: gt(7),
    insight: 'Slow detection → fix cost grows exponentially.',
    is_live_capable: false,
    sort_order: 6,
  },
  {
    category: 'quality',
    tier: 'extended',
    name: 'MTTR — Defect',
    formula_label: 'Avg(Closed − Opened) by severity',
    component_count: 1,
    component_1_label: 'Avg resolve time, worse severity (days)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(1),
    yellow_band: between(2, 3),
    red_band: gt(3),
    insight: 'Long-lived defects = growing backlog, blocked tests.',
    is_live_capable: false,
    sort_order: 7,
  },
  {
    category: 'quality',
    tier: 'extended',
    name: 'Critical Defect Aging',
    formula_label: 'Max age of open Sev1/Sev2 defects',
    component_count: 1,
    component_1_label: '# Sev1/Sev2 defects aged beyond SLA',
    component_2_label: null,
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: eq(0),
    yellow_band: eq(1),
    red_band: gte(2),
    insight: 'Zombie critical bug = escalation broken.',
    is_live_capable: false,
    sort_order: 8,
  },
  {
    category: 'quality',
    tier: 'extended',
    name: 'Code Coverage',
    formula_label: 'Lines covered / Total lines',
    component_count: 2,
    component_1_label: 'Lines covered',
    component_2_label: 'Total lines',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.8),
    yellow_band: between(0.6, 0.79),
    red_band: lt(0.6),
    insight: '< 60% = regressions hard to control.',
    is_live_capable: false,
    sort_order: 9,
  },
  {
    category: 'quality',
    tier: 'extended',
    name: 'Static Analysis Issue Density',
    formula_label: 'Critical+High issues / KLOC',
    component_count: 2,
    component_1_label: 'Critical+High issues',
    component_2_label: 'KLOC',
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(5),
    yellow_band: between(6, 15),
    red_band: gt(15),
    insight: 'Red = CI quality gate being bypassed.',
    is_live_capable: false,
    sort_order: 10,
  },
  {
    category: 'quality',
    tier: 'extended',
    name: 'Review Effectiveness',
    formula_label: 'Defects found in review / Total pre-prod',
    component_count: 2,
    component_1_label: 'Defects found in review',
    component_2_label: 'Total pre-prod defects',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.3),
    yellow_band: between(0.15, 0.29),
    red_band: lt(0.15),
    insight: 'Red = reviews are just rubber-stamping.',
    is_live_capable: false,
    sort_order: 11,
  },

  // C — Cost & Capacity (35% OHS weight) — CORE
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'Effort Consumption',
    formula_label: 'Actual Effort / Planned Effort',
    component_count: 2,
    component_1_label: 'Actual effort',
    component_2_label: 'Planned effort',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.85, 1.1),
    yellow_band: or(between(0.75, 0.84), between(1.11, 1.19)),
    red_band: or(lte(0.75), gte(1.2)),
    insight: '< 75% = under-planning; > 120% = blow-out.',
    is_live_capable: false,
    sort_order: 12,
  },
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'Margin',
    formula_label: '(Revenue − Cost) / Revenue',
    component_count: 2,
    component_1_label: 'Margin (Revenue − Cost)',
    component_2_label: 'Revenue',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: null,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.25),
    yellow_band: between(0.15, 0.24),
    red_band: lt(0.15),
    insight: '< 15% = a single risk event turns a loss.',
    is_live_capable: false,
    sort_order: 13,
  },
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'Billable Rate',
    formula_label: 'Billable Hours / Total Worked Hours',
    component_count: 2,
    component_1_label: 'Billable hours',
    component_2_label: 'Total worked hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.8),
    yellow_band: between(0.7, 0.79),
    red_band: lt(0.7),
    insight: 'Red = too much overhead, meetings, rework.',
    is_live_capable: false,
    sort_order: 14,
  },
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'Utilization Rate',
    formula_label: 'Worked Hours / Available Hours',
    component_count: 2,
    component_1_label: 'Worked hours',
    component_2_label: 'Available hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.75, 0.9),
    yellow_band: or(between(0.6, 0.74), between(0.91, 1.0)),
    red_band: or(lt(0.6), gt(1.0)),
    insight: '> 100% = burnout risk; < 60% = bench.',
    is_live_capable: true,
    sort_order: 15,
  },
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'Busy Rate',
    formula_label: 'Planned Hours / Available Hours',
    component_count: 2,
    component_1_label: 'Planned hours',
    component_2_label: 'Available hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.85, 1.1),
    yellow_band: between(1.11, 1.19),
    red_band: or(gt(1.2), lt(0.75)),
    insight: 'Early warning ahead of Utilization.',
    is_live_capable: false,
    sort_order: 16,
  },
  {
    category: 'cost_capacity',
    tier: 'core',
    name: 'eNPS / CSS',
    formula_label: 'Survey score — CSAT scale 1–5',
    component_count: 1,
    component_1_label: 'CSAT score (1–5)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 1,
    component_1_max: 5,
    is_share: false,
    green_band: gte(4.3),
    yellow_band: between(4.0, 4.29),
    red_band: lt(4.0),
    insight: 'Leading indicator of attrition and churn.',
    is_live_capable: false,
    sort_order: 17,
  },
  // C — Cost & Capacity — EXTENDED
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Cost Per Story Point',
    formula_label: 'Total Cost / Total SP Delivered',
    component_count: 2,
    component_1_label: 'Actual cost per SP',
    component_2_label: 'Baseline cost per SP',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.85, 1.15),
    yellow_band: or(between(0.7, 0.84), between(1.16, 1.3)),
    red_band: or(lt(0.7), gt(1.3)),
    insight: 'Drift = lower productivity or wrong rate-card.',
    is_live_capable: false,
    sort_order: 18,
  },
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Revenue Per BMM',
    formula_label: 'Revenue / Billable BMM',
    component_count: 2,
    component_1_label: 'Revenue per BMM (actual)',
    component_2_label: 'Baseline revenue per BMM',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: gte(1.0),
    yellow_band: between(0.85, 0.99),
    red_band: lt(0.85),
    insight: 'Track the trend rather than the absolute value.',
    is_live_capable: false,
    sort_order: 19,
  },
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Attrition Rate (rolling 12m)',
    formula_label: 'Leavers / Avg Headcount',
    component_count: 2,
    component_1_label: 'Leavers (trailing 12mo)',
    component_2_label: 'Avg headcount (trailing 12mo)',
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lt(0.1),
    yellow_band: between(0.1, 0.18),
    red_band: gt(0.18),
    insight: 'Red = knowledge loss + high onboarding cost.',
    is_live_capable: false,
    sort_order: 20,
  },
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Bench Rate',
    formula_label: 'Bench Hours / Total Available Hours',
    component_count: 2,
    component_1_label: 'Bench hours',
    component_2_label: 'Total available hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: lte(0.1),
    yellow_band: between(0.11, 0.2),
    red_band: gt(0.2),
    insight: 'Red = wrong capacity forecast or weak pipeline.',
    is_live_capable: false,
    sort_order: 21,
  },
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Overtime Ratio',
    formula_label: 'OT Hours / Standard Hours',
    component_count: 2,
    component_1_label: 'OT hours',
    component_2_label: 'Standard hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(0.05),
    yellow_band: between(0.06, 0.15),
    red_band: gt(0.15),
    insight: 'Leading indicator of burnout & quality drop.',
    is_live_capable: false,
    sort_order: 22,
  },
  {
    category: 'cost_capacity',
    tier: 'extended',
    name: 'Onboarding Ramp-up Time',
    formula_label: 'Join → first productive delivery',
    component_count: 1,
    component_1_label: 'Days join → first productive delivery',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(30),
    yellow_band: between(31, 60),
    red_band: gt(60),
    insight: 'Red = poor knowledge management.',
    is_live_capable: false,
    sort_order: 23,
  },

  // D — Delivery (25% OHS weight) — CORE
  {
    category: 'delivery',
    tier: 'core',
    name: 'On-time Delivery',
    formula_label: 'On-time Milestones / Total Milestones',
    component_count: 2,
    component_1_label: 'On-time milestones',
    component_2_label: 'Total milestones',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.9),
    yellow_band: between(0.7, 0.89),
    red_band: lt(0.7),
    insight: 'Commitment discipline — Red = delivery system failure.',
    is_live_capable: false,
    sort_order: 24,
  },
  {
    category: 'delivery',
    tier: 'core',
    name: 'Completed Effectiveness (CE)',
    formula_label: 'Std Hours Output / Actual Input Hours',
    component_count: 2,
    component_1_label: 'Std hours output',
    component_2_label: 'Actual input hours',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: gte(0.95),
    yellow_band: between(0.85, 0.94),
    red_band: lt(0.85),
    insight: 'Red = rework, waste from requirements / skill / process.',
    is_live_capable: false,
    sort_order: 25,
  },
  {
    category: 'delivery',
    tier: 'core',
    name: 'Release Predictability',
    formula_label: 'Shipped Scope / Planned Scope',
    component_count: 2,
    component_1_label: 'Shipped scope',
    component_2_label: 'Planned scope',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: gte(0.85),
    yellow_band: between(0.7, 0.84),
    red_band: lt(0.7),
    insight: 'Roadmap reliability with the business.',
    is_live_capable: false,
    sort_order: 26,
  },
  {
    category: 'delivery',
    tier: 'core',
    name: 'Schedule Performance Index (SPI)',
    formula_label: 'Earned Value / Planned Value',
    component_count: 2,
    component_1_label: 'Earned value',
    component_2_label: 'Planned value',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: between(0.95, 1.05),
    yellow_band: or(between(0.85, 0.94), between(1.06, 1.15)),
    red_band: or(lt(0.85), gt(1.15)),
    insight: '> 1.15 is also a warning — under-planning.',
    is_live_capable: false,
    sort_order: 27,
  },
  {
    category: 'delivery',
    tier: 'core',
    name: 'Forecast Accuracy',
    formula_label: '|Forecast − Actual| / Total Duration',
    component_count: 2,
    component_1_label: 'Forecast deviation |Forecast − Actual|',
    component_2_label: 'Total duration',
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(0.1),
    yellow_band: between(0.11, 0.2),
    red_band: gt(0.2),
    insight: 'Red = planning chaos or unknown risks.',
    is_live_capable: false,
    sort_order: 28,
  },
  // D — Delivery — EXTENDED
  {
    category: 'delivery',
    tier: 'extended',
    name: 'Deployment Frequency',
    formula_label: '# Production Deploys / Period',
    component_count: 2,
    component_1_label: '# production deploys',
    component_2_label: 'Period (days)',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: gte(1),
    yellow_band: between(0.033, 0.999),
    red_band: lt(0.033),
    insight: 'DORA #1 — Elite = on-demand.',
    is_live_capable: false,
    sort_order: 29,
  },
  {
    category: 'delivery',
    tier: 'extended',
    name: 'Lead Time for Changes',
    formula_label: 'Commit → Production',
    component_count: 1,
    component_1_label: 'Commit → production (days)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lt(1),
    yellow_band: between(1, 7),
    red_band: gt(7),
    insight: 'DORA #2 — pipeline agility.',
    is_live_capable: false,
    sort_order: 30,
  },
  {
    category: 'delivery',
    tier: 'extended',
    name: 'Change Failure Rate (CFR)',
    formula_label: 'Failed Deploys / Total Deploys',
    component_count: 2,
    component_1_label: 'Failed deploys',
    component_2_label: 'Total deploys',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: lte(0.05),
    yellow_band: between(0.06, 0.15),
    red_band: gt(0.15),
    insight: 'DORA #3 — Red = regression, test gap, rushed deploy.',
    is_live_capable: false,
    sort_order: 31,
  },
  {
    category: 'delivery',
    tier: 'extended',
    name: 'MTTR — Production',
    formula_label: 'Incident detect → Service restore',
    component_count: 1,
    component_1_label: 'Detect → restore (hours)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lt(1),
    yellow_band: between(1, 24),
    red_band: gt(24),
    insight: 'DORA #4 — reliability indicator.',
    is_live_capable: false,
    sort_order: 32,
  },
  {
    category: 'delivery',
    tier: 'extended',
    name: 'Time-to-Market (Feature Cycle Time)',
    formula_label: 'Idea / Discovery → Production',
    component_count: 1,
    component_1_label: 'Idea → production (weeks)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(6),
    yellow_band: between(7, 10),
    red_band: gt(10),
    insight: 'Red = features become obsolete before release.',
    is_live_capable: false,
    sort_order: 33,
  },
  {
    category: 'delivery',
    tier: 'extended',
    name: 'Customer Acceptance Lead Time',
    formula_label: 'UAT submit → Sign-off',
    component_count: 1,
    component_1_label: 'UAT submit → sign-off (days)',
    component_2_label: null,
    component_1_integer: false,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: lte(5),
    yellow_band: between(6, 10),
    red_band: gt(10),
    insight: 'Red = UAT process broken.',
    is_live_capable: false,
    sort_order: 34,
  },

  // P — Process (15% OHS weight) — CORE
  {
    category: 'process',
    tier: 'core',
    name: 'PCV (Process Compliance)',
    formula_label: 'Pass Items / Total Checklist Items',
    component_count: 2,
    component_1_label: 'Pass items',
    component_2_label: 'Total checklist items',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.9),
    yellow_band: between(0.75, 0.89),
    red_band: lt(0.75),
    insight: 'Red = process bypassed, reliance on individuals.',
    is_live_capable: false,
    sort_order: 35,
  },
  {
    category: 'process',
    tier: 'core',
    name: 'Innovation Index',
    formula_label: '# improvement initiatives applied / quarter',
    component_count: 1,
    component_1_label: '# initiatives applied this quarter',
    component_2_label: null,
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: 0,
    component_1_max: null,
    is_share: false,
    green_band: gte(2),
    yellow_band: eq(1),
    red_band: eq(0),
    insight: 'Applied = actually implemented, not just proposed.',
    is_live_capable: false,
    sort_order: 36,
  },
  {
    category: 'process',
    tier: 'core',
    name: 'Audit Compliance Rate',
    formula_label: 'Audit Items Pass / Total Items',
    component_count: 2,
    component_1_label: 'Audit items pass',
    component_2_label: 'Total items',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.95),
    yellow_band: between(0.85, 0.94),
    red_band: lt(0.85),
    insight: 'Red = risk of certification failure.',
    is_live_capable: false,
    sort_order: 37,
  },
  {
    category: 'process',
    tier: 'core',
    name: 'Retrospective Action Closure Rate',
    formula_label: 'Actions closed on time / Actions raised',
    component_count: 2,
    component_1_label: 'Actions closed on time',
    component_2_label: 'Actions raised',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.8),
    yellow_band: between(0.6, 0.79),
    red_band: lt(0.6),
    insight: 'Red = retro is just a formality.',
    is_live_capable: false,
    sort_order: 38,
  },
  // P — Process — EXTENDED
  {
    category: 'process',
    tier: 'extended',
    name: 'CAPA Closure Rate',
    formula_label: 'CAPA closed within SLA / Total raised',
    component_count: 2,
    component_1_label: 'CAPA closed within SLA',
    component_2_label: 'Total raised',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.9),
    yellow_band: between(0.75, 0.89),
    red_band: lt(0.75),
    insight: 'Red = risk accumulates → audit failure.',
    is_live_capable: false,
    sort_order: 39,
  },
  {
    category: 'process',
    tier: 'extended',
    name: 'Risk Closure Rate',
    formula_label: 'Risks closed / Total Risks',
    component_count: 2,
    component_1_label: 'Risks closed',
    component_2_label: 'Total risks',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.8),
    yellow_band: between(0.6, 0.79),
    red_band: lt(0.6),
    insight: 'Red = risk register is just a form.',
    is_live_capable: false,
    sort_order: 40,
  },
  {
    category: 'process',
    tier: 'extended',
    name: 'Risk Identification Lead Time',
    formula_label: 'Risk occurrence → register entry',
    component_count: 1,
    component_1_label: 'Days occurrence → register entry (negative = detected early)',
    component_2_label: null,
    component_1_integer: true,
    component_2_integer: false,
    component_1_min: -49,
    component_1_max: 49,
    is_share: false,
    green_band: lt(0),
    yellow_band: between(0, 7),
    red_band: gt(7),
    insight: 'Red = only recorded after it blows up.',
    is_live_capable: false,
    sort_order: 41,
  },
  {
    category: 'process',
    tier: 'extended',
    name: 'Documentation Currency Rate',
    formula_label: 'Docs updated ≤ 30 days of change / Total',
    component_count: 2,
    component_1_label: 'Docs updated within 30 days',
    component_2_label: 'Total docs',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.9),
    yellow_band: between(0.7, 0.89),
    red_band: lt(0.7),
    insight: 'Red = slow onboarding, knowledge silos.',
    is_live_capable: false,
    sort_order: 42,
  },
  {
    category: 'process',
    tier: 'extended',
    name: 'Training Compliance Rate',
    formula_label: 'Completed mandatory training / Required',
    component_count: 2,
    component_1_label: 'Completed mandatory training',
    component_2_label: 'Required training',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(1.0),
    yellow_band: between(0.85, 0.99),
    red_band: lt(0.85),
    insight: 'Red = legal & audit risk.',
    is_live_capable: false,
    sort_order: 43,
  },
  {
    category: 'process',
    tier: 'extended',
    name: 'Lessons Learned Adoption Rate',
    formula_label: 'Lessons applied / Lessons archived',
    component_count: 2,
    component_1_label: 'Lessons applied',
    component_2_label: 'Lessons archived',
    component_1_integer: true,
    component_2_integer: true,
    component_1_min: 0,
    component_1_max: null,
    is_share: true,
    green_band: gte(0.6),
    yellow_band: between(0.3, 0.59),
    red_band: lt(0.3),
    insight: 'Red = repeating the same old mistakes.',
    is_live_capable: false,
    sort_order: 44,
  },
];
