/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as routes403RouteImport } from './routes/403'
import { Route as routesAuthedRouteRouteImport } from './routes/_authed/route'
import { Route as routesLoginRouteImport } from './routes/login'
import { Route as routesAuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AdminRouteRouteImport } from './../../../packages/web-admin/src/routes/route'
import { Route as AgentRouteRouteImport } from './../../../packages/web-agent/src/routes/route'
import { Route as HiringRouteRouteImport } from './../../../packages/web-hiring/src/routes/route'
import { Route as PeopleRouteRouteImport } from './../../../packages/web-people/src/routes/route'
import { Route as PlannerRouteRouteImport } from './../../../packages/web-planner/src/routes/route'
import { Route as PmRouteRouteImport } from './../../../packages/web-pm/src/routes/route'
import { Route as routesAuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AdminIndexRouteImport } from './../../../packages/web-admin/src/routes/index'
import { Route as AdminAuditRouteImport } from './../../../packages/web-admin/src/routes/audit'
import { Route as AdminGroupsRouteImport } from './../../../packages/web-admin/src/routes/groups'
import { Route as AdminM365DirectoryRouteImport } from './../../../packages/web-admin/src/routes/m365-directory'
import { Route as AdminMailRouteImport } from './../../../packages/web-admin/src/routes/mail'
import { Route as AdminNotificationsRouteImport } from './../../../packages/web-admin/src/routes/notifications'
import { Route as AdminRoleAccessRouteImport } from './../../../packages/web-admin/src/routes/role-access'
import { Route as AdminSkillsRouteImport } from './../../../packages/web-admin/src/routes/skills'
import { Route as AdminSsoRouteImport } from './../../../packages/web-admin/src/routes/sso'
import { Route as AdminTenantRouteImport } from './../../../packages/web-admin/src/routes/tenant'
import { Route as AdminUsersRouteImport } from './../../../packages/web-admin/src/routes/users'
import { Route as AgentIndexRouteImport } from './../../../packages/web-agent/src/routes/index'
import { Route as AgentChatRouteImport } from './../../../packages/web-agent/src/routes/chat'
import { Route as AgentKnowledgeRouteImport } from './../../../packages/web-agent/src/routes/knowledge'
import { Route as AgentWorkflowsRouteRouteImport } from './../../../packages/web-agent/src/routes/workflows/route'
import { Route as HiringIndexRouteImport } from './../../../packages/web-hiring/src/routes/index'
import { Route as PeopleIndexRouteImport } from './../../../packages/web-people/src/routes/index'
import { Route as PeopleAllocationRouteImport } from './../../../packages/web-people/src/routes/allocation'
import { Route as PeopleOffboardingRouteImport } from './../../../packages/web-people/src/routes/offboarding'
import { Route as PeopleOnboardingRouteImport } from './../../../packages/web-people/src/routes/onboarding'
import { Route as PeopleOrgRouteImport } from './../../../packages/web-people/src/routes/org'
import { Route as PeoplePerformanceRouteRouteImport } from './../../../packages/web-people/src/routes/performance/route'
import { Route as PeopleProbationRouteImport } from './../../../packages/web-people/src/routes/probation'
import { Route as PlannerIndexRouteImport } from './../../../packages/web-planner/src/routes/index'
import { Route as PlannerGroupsRouteImport } from './../../../packages/web-planner/src/routes/groups'
import { Route as PlannerMyTasksRouteImport } from './../../../packages/web-planner/src/routes/my-tasks'
import { Route as PlannerTrashRouteImport } from './../../../packages/web-planner/src/routes/trash'
import { Route as PmIndexRouteImport } from './../../../packages/web-pm/src/routes/index'
import { Route as routesAuthedSettingsAvailabilityRouteImport } from './routes/_authed/settings/availability'
import { Route as routesAuthedSettingsNotificationsRouteImport } from './routes/_authed/settings/notifications'
import { Route as routesAuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as routesAuthedSettingsRolesRouteImport } from './routes/_authed/settings/roles'
import { Route as routesAuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as routesAuthedSettingsSkillsRouteImport } from './routes/_authed/settings/skills'
import { Route as AgentWorkflowsIndexRouteImport } from './../../../packages/web-agent/src/routes/workflows/index'
import { Route as HiringCandidatesIndexRouteImport } from './../../../packages/web-hiring/src/routes/candidates/index'
import { Route as HiringInterviewsIndexRouteImport } from './../../../packages/web-hiring/src/routes/interviews/index'
import { Route as HiringKnowledgeIndexRouteImport } from './../../../packages/web-hiring/src/routes/knowledge/index'
import { Route as HiringRequisitionsIndexRouteImport } from './../../../packages/web-hiring/src/routes/requisitions/index'
import { Route as HiringRequisitionsRequisitionIdRouteImport } from './../../../packages/web-hiring/src/routes/requisitions/$requisitionId'
import { Route as HiringSettingsIndexRouteImport } from './../../../packages/web-hiring/src/routes/settings/index'
import { Route as PeopleEmployeesIndexRouteImport } from './../../../packages/web-people/src/routes/employees/index'
import { Route as PeopleEmployeesWorkerIdRouteImport } from './../../../packages/web-people/src/routes/employees/$workerId'
import { Route as PeoplePerformanceIndexRouteImport } from './../../../packages/web-people/src/routes/performance/index'
import { Route as PeoplePerformanceAuditRouteImport } from './../../../packages/web-people/src/routes/performance/audit'
import { Route as PeoplePerformanceConfigurationRouteImport } from './../../../packages/web-people/src/routes/performance/configuration'
import { Route as PeoplePerformanceCycleRouteImport } from './../../../packages/web-people/src/routes/performance/cycle'
import { Route as PeoplePerformanceHistoryRouteImport } from './../../../packages/web-people/src/routes/performance/history'
import { Route as PeoplePerformanceMoraleRouteImport } from './../../../packages/web-people/src/routes/performance/morale'
import { Route as PeoplePerformanceScoringRouteImport } from './../../../packages/web-people/src/routes/performance/scoring'
import { Route as PeoplePerformanceSelfAssessmentRouteImport } from './../../../packages/web-people/src/routes/performance/self-assessment'
import { Route as PlannerGroupsGroupIdRouteImport } from './../../../packages/web-planner/src/routes/groups_/$groupId'
import { Route as PlannerGroupsDiscoverRouteImport } from './../../../packages/web-planner/src/routes/groups_/discover'
import { Route as PlannerPlansPlanIdRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId'
import { Route as PmAccountsIndexRouteImport } from './../../../packages/web-pm/src/routes/accounts/index'
import { Route as PmAccountsAccountIdRouteImport } from './../../../packages/web-pm/src/routes/accounts/$accountId'
import { Route as PmMetricsIndexRouteImport } from './../../../packages/web-pm/src/routes/metrics/index'
import { Route as PmProjectsIndexRouteImport } from './../../../packages/web-pm/src/routes/projects/index'
import { Route as PmProjectsProjectIdRouteImport } from './../../../packages/web-pm/src/routes/projects/$projectId'
import { Route as PmRequestsIndexRouteImport } from './../../../packages/web-pm/src/routes/requests/index'
import { Route as PmRequestsCharterIdRouteImport } from './../../../packages/web-pm/src/routes/requests/$charterId'
import { Route as PmResourcingIndexRouteImport } from './../../../packages/web-pm/src/routes/resourcing/index'
import { Route as PmRisksIndexRouteImport } from './../../../packages/web-pm/src/routes/risks/index'
import { Route as PmWeeklyIndexRouteImport } from './../../../packages/web-pm/src/routes/weekly/index'
import { Route as AgentWorkflowsRunsRunIdRouteImport } from './../../../packages/web-agent/src/routes/workflows/runs/$runId'
import { Route as PlannerPlansPlanIdSettingsCategoriesRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId_/settings_/categories'
import { Route as PlannerPlansPlanIdTasksTaskIdRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId_/tasks_/$taskId'

const routes403Route = routes403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const routesAuthedRouteRoute = routesAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const routesLoginRoute = routesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const routesAuthedIndexRoute = routesAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const HiringRouteRoute = HiringRouteRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PeopleRouteRoute = PeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PlannerRouteRoute = PlannerRouteRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PmRouteRoute = PmRouteRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const routesAuthedSettingsIndexRoute =
  routesAuthedSettingsIndexRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminM365DirectoryRoute = AdminM365DirectoryRouteImport.update({
  id: '/m365-directory',
  path: '/m365-directory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleAccessRoute = AdminRoleAccessRouteImport.update({
  id: '/role-access',
  path: '/role-access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSsoRoute = AdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantRoute = AdminTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentKnowledgeRoute = AgentKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentWorkflowsRouteRoute = AgentWorkflowsRouteRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AgentRouteRoute,
} as any)
const HiringIndexRoute = HiringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleAllocationRoute = PeopleAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleOffboardingRoute = PeopleOffboardingRouteImport.update({
  id: '/offboarding',
  path: '/offboarding',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleOnboardingRoute = PeopleOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleOrgRoute = PeopleOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeoplePerformanceRouteRoute = PeoplePerformanceRouteRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleProbationRoute = PeopleProbationRouteImport.update({
  id: '/probation',
  path: '/probation',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerGroupsRoute = PlannerGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerMyTasksRoute = PlannerMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerTrashRoute = PlannerTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PmIndexRoute = PmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmRouteRoute,
} as any)
const routesAuthedSettingsAvailabilityRoute =
  routesAuthedSettingsAvailabilityRouteImport.update({
    id: '/settings/availability',
    path: '/settings/availability',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const routesAuthedSettingsNotificationsRoute =
  routesAuthedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const routesAuthedSettingsProfileRoute =
  routesAuthedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const routesAuthedSettingsRolesRoute =
  routesAuthedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const routesAuthedSettingsSecurityRoute =
  routesAuthedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const routesAuthedSettingsSkillsRoute =
  routesAuthedSettingsSkillsRouteImport.update({
    id: '/settings/skills',
    path: '/settings/skills',
    getParentRoute: () => routesAuthedRouteRoute,
  } as any)
const AgentWorkflowsIndexRoute = AgentWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentWorkflowsRouteRoute,
} as any)
const HiringCandidatesIndexRoute = HiringCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringInterviewsIndexRoute = HiringInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringKnowledgeIndexRoute = HiringKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringRequisitionsIndexRoute = HiringRequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringRequisitionsRequisitionIdRoute =
  HiringRequisitionsRequisitionIdRouteImport.update({
    id: '/requisitions/$requisitionId',
    path: '/requisitions/$requisitionId',
    getParentRoute: () => HiringRouteRoute,
  } as any)
const HiringSettingsIndexRoute = HiringSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const PeopleEmployeesIndexRoute = PeopleEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleEmployeesWorkerIdRoute = PeopleEmployeesWorkerIdRouteImport.update({
  id: '/employees/$workerId',
  path: '/employees/$workerId',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeoplePerformanceIndexRoute = PeoplePerformanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeoplePerformanceRouteRoute,
} as any)
const PeoplePerformanceAuditRoute = PeoplePerformanceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PeoplePerformanceRouteRoute,
} as any)
const PeoplePerformanceConfigurationRoute =
  PeoplePerformanceConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => PeoplePerformanceRouteRoute,
  } as any)
const PeoplePerformanceCycleRoute = PeoplePerformanceCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => PeoplePerformanceRouteRoute,
} as any)
const PeoplePerformanceHistoryRoute =
  PeoplePerformanceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => PeoplePerformanceRouteRoute,
  } as any)
const PeoplePerformanceMoraleRoute = PeoplePerformanceMoraleRouteImport.update({
  id: '/morale',
  path: '/morale',
  getParentRoute: () => PeoplePerformanceRouteRoute,
} as any)
const PeoplePerformanceScoringRoute =
  PeoplePerformanceScoringRouteImport.update({
    id: '/scoring',
    path: '/scoring',
    getParentRoute: () => PeoplePerformanceRouteRoute,
  } as any)
const PeoplePerformanceSelfAssessmentRoute =
  PeoplePerformanceSelfAssessmentRouteImport.update({
    id: '/self-assessment',
    path: '/self-assessment',
    getParentRoute: () => PeoplePerformanceRouteRoute,
  } as any)
const PlannerGroupsGroupIdRoute = PlannerGroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerGroupsDiscoverRoute = PlannerGroupsDiscoverRouteImport.update({
  id: '/groups_/discover',
  path: '/groups/discover',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerPlansPlanIdRoute = PlannerPlansPlanIdRouteImport.update({
  id: '/plans_/$planId',
  path: '/plans/$planId',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PmAccountsIndexRoute = PmAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmAccountsAccountIdRoute = PmAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmMetricsIndexRoute = PmMetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmProjectsIndexRoute = PmProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmProjectsProjectIdRoute = PmProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmRequestsIndexRoute = PmRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmRequestsCharterIdRoute = PmRequestsCharterIdRouteImport.update({
  id: '/requests/$charterId',
  path: '/requests/$charterId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmResourcingIndexRoute = PmResourcingIndexRouteImport.update({
  id: '/resourcing/',
  path: '/resourcing/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmRisksIndexRoute = PmRisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmWeeklyIndexRoute = PmWeeklyIndexRouteImport.update({
  id: '/weekly/',
  path: '/weekly/',
  getParentRoute: () => PmRouteRoute,
} as any)
const AgentWorkflowsRunsRunIdRoute = AgentWorkflowsRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AgentWorkflowsRouteRoute,
} as any)
const PlannerPlansPlanIdSettingsCategoriesRoute =
  PlannerPlansPlanIdSettingsCategoriesRouteImport.update({
    id: '/plans_/$planId_/settings_/categories',
    path: '/plans/$planId/settings/categories',
    getParentRoute: () => PlannerRouteRoute,
  } as any)
const PlannerPlansPlanIdTasksTaskIdRoute =
  PlannerPlansPlanIdTasksTaskIdRouteImport.update({
    id: '/plans_/$planId_/tasks_/$taskId',
    path: '/plans/$planId/tasks/$taskId',
    getParentRoute: () => PlannerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof routesAuthedIndexRoute
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/hiring': typeof HiringRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/planner': typeof PlannerRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/settings': typeof routesAuthedSettingsIndexRoute
  '/agent/workflows': typeof AgentWorkflowsRouteRouteWithChildren
  '/people/performance': typeof PeoplePerformanceRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/m365-directory': typeof AdminM365DirectoryRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/role-access': typeof AdminRoleAccessRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/people/allocation': typeof PeopleAllocationRoute
  '/people/offboarding': typeof PeopleOffboardingRoute
  '/people/onboarding': typeof PeopleOnboardingRoute
  '/people/org': typeof PeopleOrgRoute
  '/people/probation': typeof PeopleProbationRoute
  '/planner/groups': typeof PlannerGroupsRoute
  '/planner/my-tasks': typeof PlannerMyTasksRoute
  '/planner/trash': typeof PlannerTrashRoute
  '/settings/availability': typeof routesAuthedSettingsAvailabilityRoute
  '/settings/notifications': typeof routesAuthedSettingsNotificationsRoute
  '/settings/profile': typeof routesAuthedSettingsProfileRoute
  '/settings/roles': typeof routesAuthedSettingsRolesRoute
  '/settings/security': typeof routesAuthedSettingsSecurityRoute
  '/settings/skills': typeof routesAuthedSettingsSkillsRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/hiring/': typeof HiringIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/pm/': typeof PmIndexRoute
  '/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/people/employees/$workerId': typeof PeopleEmployeesWorkerIdRoute
  '/people/performance/audit': typeof PeoplePerformanceAuditRoute
  '/people/performance/configuration': typeof PeoplePerformanceConfigurationRoute
  '/people/performance/cycle': typeof PeoplePerformanceCycleRoute
  '/people/performance/history': typeof PeoplePerformanceHistoryRoute
  '/people/performance/morale': typeof PeoplePerformanceMoraleRoute
  '/people/performance/scoring': typeof PeoplePerformanceScoringRoute
  '/people/performance/self-assessment': typeof PeoplePerformanceSelfAssessmentRoute
  '/planner/groups/$groupId': typeof PlannerGroupsGroupIdRoute
  '/planner/groups/discover': typeof PlannerGroupsDiscoverRoute
  '/planner/plans/$planId': typeof PlannerPlansPlanIdRoute
  '/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/agent/workflows/': typeof AgentWorkflowsIndexRoute
  '/hiring/candidates/': typeof HiringCandidatesIndexRoute
  '/hiring/interviews/': typeof HiringInterviewsIndexRoute
  '/hiring/knowledge/': typeof HiringKnowledgeIndexRoute
  '/hiring/requisitions/': typeof HiringRequisitionsIndexRoute
  '/hiring/settings/': typeof HiringSettingsIndexRoute
  '/people/employees/': typeof PeopleEmployeesIndexRoute
  '/people/performance/': typeof PeoplePerformanceIndexRoute
  '/pm/accounts/': typeof PmAccountsIndexRoute
  '/pm/metrics/': typeof PmMetricsIndexRoute
  '/pm/projects/': typeof PmProjectsIndexRoute
  '/pm/requests/': typeof PmRequestsIndexRoute
  '/pm/resourcing/': typeof PmResourcingIndexRoute
  '/pm/risks/': typeof PmRisksIndexRoute
  '/pm/weekly/': typeof PmWeeklyIndexRoute
  '/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/planner/plans/$planId/settings/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/planner/plans/$planId/tasks/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/': typeof routesAuthedIndexRoute
  '/settings': typeof routesAuthedSettingsIndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/m365-directory': typeof AdminM365DirectoryRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/role-access': typeof AdminRoleAccessRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/people/allocation': typeof PeopleAllocationRoute
  '/people/offboarding': typeof PeopleOffboardingRoute
  '/people/onboarding': typeof PeopleOnboardingRoute
  '/people/org': typeof PeopleOrgRoute
  '/people/probation': typeof PeopleProbationRoute
  '/planner/groups': typeof PlannerGroupsRoute
  '/planner/my-tasks': typeof PlannerMyTasksRoute
  '/planner/trash': typeof PlannerTrashRoute
  '/settings/availability': typeof routesAuthedSettingsAvailabilityRoute
  '/settings/notifications': typeof routesAuthedSettingsNotificationsRoute
  '/settings/profile': typeof routesAuthedSettingsProfileRoute
  '/settings/roles': typeof routesAuthedSettingsRolesRoute
  '/settings/security': typeof routesAuthedSettingsSecurityRoute
  '/settings/skills': typeof routesAuthedSettingsSkillsRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/hiring': typeof HiringIndexRoute
  '/people': typeof PeopleIndexRoute
  '/planner': typeof PlannerIndexRoute
  '/pm': typeof PmIndexRoute
  '/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/people/employees/$workerId': typeof PeopleEmployeesWorkerIdRoute
  '/people/performance/audit': typeof PeoplePerformanceAuditRoute
  '/people/performance/configuration': typeof PeoplePerformanceConfigurationRoute
  '/people/performance/cycle': typeof PeoplePerformanceCycleRoute
  '/people/performance/history': typeof PeoplePerformanceHistoryRoute
  '/people/performance/morale': typeof PeoplePerformanceMoraleRoute
  '/people/performance/scoring': typeof PeoplePerformanceScoringRoute
  '/people/performance/self-assessment': typeof PeoplePerformanceSelfAssessmentRoute
  '/planner/groups/$groupId': typeof PlannerGroupsGroupIdRoute
  '/planner/groups/discover': typeof PlannerGroupsDiscoverRoute
  '/planner/plans/$planId': typeof PlannerPlansPlanIdRoute
  '/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/agent/workflows': typeof AgentWorkflowsIndexRoute
  '/hiring/candidates': typeof HiringCandidatesIndexRoute
  '/hiring/interviews': typeof HiringInterviewsIndexRoute
  '/hiring/knowledge': typeof HiringKnowledgeIndexRoute
  '/hiring/requisitions': typeof HiringRequisitionsIndexRoute
  '/hiring/settings': typeof HiringSettingsIndexRoute
  '/people/employees': typeof PeopleEmployeesIndexRoute
  '/people/performance': typeof PeoplePerformanceIndexRoute
  '/pm/accounts': typeof PmAccountsIndexRoute
  '/pm/metrics': typeof PmMetricsIndexRoute
  '/pm/projects': typeof PmProjectsIndexRoute
  '/pm/requests': typeof PmRequestsIndexRoute
  '/pm/resourcing': typeof PmResourcingIndexRoute
  '/pm/risks': typeof PmRisksIndexRoute
  '/pm/weekly': typeof PmWeeklyIndexRoute
  '/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/planner/plans/$planId/settings/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/planner/plans/$planId/tasks/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof routesAuthedRouteRouteWithChildren
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/_authed/admin': typeof AdminRouteRouteWithChildren
  '/_authed/agent': typeof AgentRouteRouteWithChildren
  '/_authed/hiring': typeof HiringRouteRouteWithChildren
  '/_authed/people': typeof PeopleRouteRouteWithChildren
  '/_authed/planner': typeof PlannerRouteRouteWithChildren
  '/_authed/pm': typeof PmRouteRouteWithChildren
  '/_authed/': typeof routesAuthedIndexRoute
  '/_authed/settings': typeof routesAuthedSettingsIndexRoute
  '/_authed/agent/workflows': typeof AgentWorkflowsRouteRouteWithChildren
  '/_authed/people/performance': typeof PeoplePerformanceRouteRouteWithChildren
  '/_authed/admin/audit': typeof AdminAuditRoute
  '/_authed/admin/groups': typeof AdminGroupsRoute
  '/_authed/admin/m365-directory': typeof AdminM365DirectoryRoute
  '/_authed/admin/mail': typeof AdminMailRoute
  '/_authed/admin/notifications': typeof AdminNotificationsRoute
  '/_authed/admin/role-access': typeof AdminRoleAccessRoute
  '/_authed/admin/skills': typeof AdminSkillsRoute
  '/_authed/admin/sso': typeof AdminSsoRoute
  '/_authed/admin/tenant': typeof AdminTenantRoute
  '/_authed/admin/users': typeof AdminUsersRoute
  '/_authed/agent/chat': typeof AgentChatRoute
  '/_authed/agent/knowledge': typeof AgentKnowledgeRoute
  '/_authed/people/allocation': typeof PeopleAllocationRoute
  '/_authed/people/offboarding': typeof PeopleOffboardingRoute
  '/_authed/people/onboarding': typeof PeopleOnboardingRoute
  '/_authed/people/org': typeof PeopleOrgRoute
  '/_authed/people/probation': typeof PeopleProbationRoute
  '/_authed/planner/groups': typeof PlannerGroupsRoute
  '/_authed/planner/my-tasks': typeof PlannerMyTasksRoute
  '/_authed/planner/trash': typeof PlannerTrashRoute
  '/_authed/settings/availability': typeof routesAuthedSettingsAvailabilityRoute
  '/_authed/settings/notifications': typeof routesAuthedSettingsNotificationsRoute
  '/_authed/settings/profile': typeof routesAuthedSettingsProfileRoute
  '/_authed/settings/roles': typeof routesAuthedSettingsRolesRoute
  '/_authed/settings/security': typeof routesAuthedSettingsSecurityRoute
  '/_authed/settings/skills': typeof routesAuthedSettingsSkillsRoute
  '/_authed/admin/': typeof AdminIndexRoute
  '/_authed/agent/': typeof AgentIndexRoute
  '/_authed/hiring/': typeof HiringIndexRoute
  '/_authed/people/': typeof PeopleIndexRoute
  '/_authed/planner/': typeof PlannerIndexRoute
  '/_authed/pm/': typeof PmIndexRoute
  '/_authed/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/_authed/people/employees/$workerId': typeof PeopleEmployeesWorkerIdRoute
  '/_authed/people/performance/audit': typeof PeoplePerformanceAuditRoute
  '/_authed/people/performance/configuration': typeof PeoplePerformanceConfigurationRoute
  '/_authed/people/performance/cycle': typeof PeoplePerformanceCycleRoute
  '/_authed/people/performance/history': typeof PeoplePerformanceHistoryRoute
  '/_authed/people/performance/morale': typeof PeoplePerformanceMoraleRoute
  '/_authed/people/performance/scoring': typeof PeoplePerformanceScoringRoute
  '/_authed/people/performance/self-assessment': typeof PeoplePerformanceSelfAssessmentRoute
  '/_authed/planner/groups_/$groupId': typeof PlannerGroupsGroupIdRoute
  '/_authed/planner/groups_/discover': typeof PlannerGroupsDiscoverRoute
  '/_authed/planner/plans_/$planId': typeof PlannerPlansPlanIdRoute
  '/_authed/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/_authed/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/_authed/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/_authed/agent/workflows/': typeof AgentWorkflowsIndexRoute
  '/_authed/hiring/candidates/': typeof HiringCandidatesIndexRoute
  '/_authed/hiring/interviews/': typeof HiringInterviewsIndexRoute
  '/_authed/hiring/knowledge/': typeof HiringKnowledgeIndexRoute
  '/_authed/hiring/requisitions/': typeof HiringRequisitionsIndexRoute
  '/_authed/hiring/settings/': typeof HiringSettingsIndexRoute
  '/_authed/people/employees/': typeof PeopleEmployeesIndexRoute
  '/_authed/people/performance/': typeof PeoplePerformanceIndexRoute
  '/_authed/pm/accounts/': typeof PmAccountsIndexRoute
  '/_authed/pm/metrics/': typeof PmMetricsIndexRoute
  '/_authed/pm/projects/': typeof PmProjectsIndexRoute
  '/_authed/pm/requests/': typeof PmRequestsIndexRoute
  '/_authed/pm/resourcing/': typeof PmResourcingIndexRoute
  '/_authed/pm/risks/': typeof PmRisksIndexRoute
  '/_authed/pm/weekly/': typeof PmWeeklyIndexRoute
  '/_authed/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/_authed/planner/plans_/$planId_/settings_/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/_authed/planner/plans_/$planId_/tasks_/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/admin'
    | '/agent'
    | '/hiring'
    | '/people'
    | '/planner'
    | '/pm'
    | '/settings'
    | '/agent/workflows'
    | '/people/performance'
    | '/admin/audit'
    | '/admin/groups'
    | '/admin/m365-directory'
    | '/admin/mail'
    | '/admin/notifications'
    | '/admin/role-access'
    | '/admin/skills'
    | '/admin/sso'
    | '/admin/tenant'
    | '/admin/users'
    | '/agent/chat'
    | '/agent/knowledge'
    | '/people/allocation'
    | '/people/offboarding'
    | '/people/onboarding'
    | '/people/org'
    | '/people/probation'
    | '/planner/groups'
    | '/planner/my-tasks'
    | '/planner/trash'
    | '/settings/availability'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/skills'
    | '/admin/'
    | '/agent/'
    | '/hiring/'
    | '/people/'
    | '/planner/'
    | '/pm/'
    | '/hiring/requisitions/$requisitionId'
    | '/people/employees/$workerId'
    | '/people/performance/audit'
    | '/people/performance/configuration'
    | '/people/performance/cycle'
    | '/people/performance/history'
    | '/people/performance/morale'
    | '/people/performance/scoring'
    | '/people/performance/self-assessment'
    | '/planner/groups/$groupId'
    | '/planner/groups/discover'
    | '/planner/plans/$planId'
    | '/pm/accounts/$accountId'
    | '/pm/projects/$projectId'
    | '/pm/requests/$charterId'
    | '/agent/workflows/'
    | '/hiring/candidates/'
    | '/hiring/interviews/'
    | '/hiring/knowledge/'
    | '/hiring/requisitions/'
    | '/hiring/settings/'
    | '/people/employees/'
    | '/people/performance/'
    | '/pm/accounts/'
    | '/pm/metrics/'
    | '/pm/projects/'
    | '/pm/requests/'
    | '/pm/resourcing/'
    | '/pm/risks/'
    | '/pm/weekly/'
    | '/agent/workflows/runs/$runId'
    | '/planner/plans/$planId/settings/categories'
    | '/planner/plans/$planId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/'
    | '/settings'
    | '/admin/audit'
    | '/admin/groups'
    | '/admin/m365-directory'
    | '/admin/mail'
    | '/admin/notifications'
    | '/admin/role-access'
    | '/admin/skills'
    | '/admin/sso'
    | '/admin/tenant'
    | '/admin/users'
    | '/agent/chat'
    | '/agent/knowledge'
    | '/people/allocation'
    | '/people/offboarding'
    | '/people/onboarding'
    | '/people/org'
    | '/people/probation'
    | '/planner/groups'
    | '/planner/my-tasks'
    | '/planner/trash'
    | '/settings/availability'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/skills'
    | '/admin'
    | '/agent'
    | '/hiring'
    | '/people'
    | '/planner'
    | '/pm'
    | '/hiring/requisitions/$requisitionId'
    | '/people/employees/$workerId'
    | '/people/performance/audit'
    | '/people/performance/configuration'
    | '/people/performance/cycle'
    | '/people/performance/history'
    | '/people/performance/morale'
    | '/people/performance/scoring'
    | '/people/performance/self-assessment'
    | '/planner/groups/$groupId'
    | '/planner/groups/discover'
    | '/planner/plans/$planId'
    | '/pm/accounts/$accountId'
    | '/pm/projects/$projectId'
    | '/pm/requests/$charterId'
    | '/agent/workflows'
    | '/hiring/candidates'
    | '/hiring/interviews'
    | '/hiring/knowledge'
    | '/hiring/requisitions'
    | '/hiring/settings'
    | '/people/employees'
    | '/people/performance'
    | '/pm/accounts'
    | '/pm/metrics'
    | '/pm/projects'
    | '/pm/requests'
    | '/pm/resourcing'
    | '/pm/risks'
    | '/pm/weekly'
    | '/agent/workflows/runs/$runId'
    | '/planner/plans/$planId/settings/categories'
    | '/planner/plans/$planId/tasks/$taskId'
  id:
    | '__root__'
    | '/_authed'
    | '/403'
    | '/login'
    | '/_authed/admin'
    | '/_authed/agent'
    | '/_authed/hiring'
    | '/_authed/people'
    | '/_authed/planner'
    | '/_authed/pm'
    | '/_authed/'
    | '/_authed/settings'
    | '/_authed/agent/workflows'
    | '/_authed/people/performance'
    | '/_authed/admin/audit'
    | '/_authed/admin/groups'
    | '/_authed/admin/m365-directory'
    | '/_authed/admin/mail'
    | '/_authed/admin/notifications'
    | '/_authed/admin/role-access'
    | '/_authed/admin/skills'
    | '/_authed/admin/sso'
    | '/_authed/admin/tenant'
    | '/_authed/admin/users'
    | '/_authed/agent/chat'
    | '/_authed/agent/knowledge'
    | '/_authed/people/allocation'
    | '/_authed/people/offboarding'
    | '/_authed/people/onboarding'
    | '/_authed/people/org'
    | '/_authed/people/probation'
    | '/_authed/planner/groups'
    | '/_authed/planner/my-tasks'
    | '/_authed/planner/trash'
    | '/_authed/settings/availability'
    | '/_authed/settings/notifications'
    | '/_authed/settings/profile'
    | '/_authed/settings/roles'
    | '/_authed/settings/security'
    | '/_authed/settings/skills'
    | '/_authed/admin/'
    | '/_authed/agent/'
    | '/_authed/hiring/'
    | '/_authed/people/'
    | '/_authed/planner/'
    | '/_authed/pm/'
    | '/_authed/hiring/requisitions/$requisitionId'
    | '/_authed/people/employees/$workerId'
    | '/_authed/people/performance/audit'
    | '/_authed/people/performance/configuration'
    | '/_authed/people/performance/cycle'
    | '/_authed/people/performance/history'
    | '/_authed/people/performance/morale'
    | '/_authed/people/performance/scoring'
    | '/_authed/people/performance/self-assessment'
    | '/_authed/planner/groups_/$groupId'
    | '/_authed/planner/groups_/discover'
    | '/_authed/planner/plans_/$planId'
    | '/_authed/pm/accounts/$accountId'
    | '/_authed/pm/projects/$projectId'
    | '/_authed/pm/requests/$charterId'
    | '/_authed/agent/workflows/'
    | '/_authed/hiring/candidates/'
    | '/_authed/hiring/interviews/'
    | '/_authed/hiring/knowledge/'
    | '/_authed/hiring/requisitions/'
    | '/_authed/hiring/settings/'
    | '/_authed/people/employees/'
    | '/_authed/people/performance/'
    | '/_authed/pm/accounts/'
    | '/_authed/pm/metrics/'
    | '/_authed/pm/projects/'
    | '/_authed/pm/requests/'
    | '/_authed/pm/resourcing/'
    | '/_authed/pm/risks/'
    | '/_authed/pm/weekly/'
    | '/_authed/agent/workflows/runs/$runId'
    | '/_authed/planner/plans_/$planId_/settings_/categories'
    | '/_authed/planner/plans_/$planId_/tasks_/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  routesAuthedRouteRoute: typeof routesAuthedRouteRouteWithChildren
  routes403Route: typeof routes403Route
  routesLoginRoute: typeof routesLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof routes403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routesAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof routesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof routesAuthedIndexRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/agent': {
      id: '/_authed/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/hiring': {
      id: '/_authed/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/planner': {
      id: '/_authed/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/pm': {
      id: '/_authed/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof routesAuthedSettingsIndexRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/groups': {
      id: '/_authed/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/m365-directory': {
      id: '/_authed/admin/m365-directory'
      path: '/m365-directory'
      fullPath: '/admin/m365-directory'
      preLoaderRoute: typeof AdminM365DirectoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/mail': {
      id: '/_authed/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/notifications': {
      id: '/_authed/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/role-access': {
      id: '/_authed/admin/role-access'
      path: '/role-access'
      fullPath: '/admin/role-access'
      preLoaderRoute: typeof AdminRoleAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/skills': {
      id: '/_authed/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/sso': {
      id: '/_authed/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AdminSsoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/tenant': {
      id: '/_authed/admin/tenant'
      path: '/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AdminTenantRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/agent/': {
      id: '/_authed/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/agent/chat': {
      id: '/_authed/agent/chat'
      path: '/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/agent/knowledge': {
      id: '/_authed/agent/knowledge'
      path: '/knowledge'
      fullPath: '/agent/knowledge'
      preLoaderRoute: typeof AgentKnowledgeRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/agent/workflows': {
      id: '/_authed/agent/workflows'
      path: '/workflows'
      fullPath: '/agent/workflows'
      preLoaderRoute: typeof AgentWorkflowsRouteRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/hiring/': {
      id: '/_authed/hiring/'
      path: '/'
      fullPath: '/hiring/'
      preLoaderRoute: typeof HiringIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/allocation': {
      id: '/_authed/people/allocation'
      path: '/allocation'
      fullPath: '/people/allocation'
      preLoaderRoute: typeof PeopleAllocationRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/offboarding': {
      id: '/_authed/people/offboarding'
      path: '/offboarding'
      fullPath: '/people/offboarding'
      preLoaderRoute: typeof PeopleOffboardingRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/onboarding': {
      id: '/_authed/people/onboarding'
      path: '/onboarding'
      fullPath: '/people/onboarding'
      preLoaderRoute: typeof PeopleOnboardingRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/org': {
      id: '/_authed/people/org'
      path: '/org'
      fullPath: '/people/org'
      preLoaderRoute: typeof PeopleOrgRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/performance': {
      id: '/_authed/people/performance'
      path: '/performance'
      fullPath: '/people/performance'
      preLoaderRoute: typeof PeoplePerformanceRouteRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/probation': {
      id: '/_authed/people/probation'
      path: '/probation'
      fullPath: '/people/probation'
      preLoaderRoute: typeof PeopleProbationRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/planner/': {
      id: '/_authed/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/groups': {
      id: '/_authed/planner/groups'
      path: '/groups'
      fullPath: '/planner/groups'
      preLoaderRoute: typeof PlannerGroupsRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/my-tasks': {
      id: '/_authed/planner/my-tasks'
      path: '/my-tasks'
      fullPath: '/planner/my-tasks'
      preLoaderRoute: typeof PlannerMyTasksRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/trash': {
      id: '/_authed/planner/trash'
      path: '/trash'
      fullPath: '/planner/trash'
      preLoaderRoute: typeof PlannerTrashRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/pm/': {
      id: '/_authed/pm/'
      path: '/'
      fullPath: '/pm/'
      preLoaderRoute: typeof PmIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/settings/availability': {
      id: '/_authed/settings/availability'
      path: '/settings/availability'
      fullPath: '/settings/availability'
      preLoaderRoute: typeof routesAuthedSettingsAvailabilityRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof routesAuthedSettingsNotificationsRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof routesAuthedSettingsProfileRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings/roles': {
      id: '/_authed/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof routesAuthedSettingsRolesRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof routesAuthedSettingsSecurityRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/settings/skills': {
      id: '/_authed/settings/skills'
      path: '/settings/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof routesAuthedSettingsSkillsRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/agent/workflows/': {
      id: '/_authed/agent/workflows/'
      path: '/'
      fullPath: '/agent/workflows/'
      preLoaderRoute: typeof AgentWorkflowsIndexRouteImport
      parentRoute: typeof AgentWorkflowsRouteRoute
    }
    '/_authed/hiring/candidates/': {
      id: '/_authed/hiring/candidates/'
      path: '/candidates'
      fullPath: '/hiring/candidates/'
      preLoaderRoute: typeof HiringCandidatesIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/interviews/': {
      id: '/_authed/hiring/interviews/'
      path: '/interviews'
      fullPath: '/hiring/interviews/'
      preLoaderRoute: typeof HiringInterviewsIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/knowledge/': {
      id: '/_authed/hiring/knowledge/'
      path: '/knowledge'
      fullPath: '/hiring/knowledge/'
      preLoaderRoute: typeof HiringKnowledgeIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/requisitions/': {
      id: '/_authed/hiring/requisitions/'
      path: '/requisitions'
      fullPath: '/hiring/requisitions/'
      preLoaderRoute: typeof HiringRequisitionsIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/requisitions/$requisitionId': {
      id: '/_authed/hiring/requisitions/$requisitionId'
      path: '/requisitions/$requisitionId'
      fullPath: '/hiring/requisitions/$requisitionId'
      preLoaderRoute: typeof HiringRequisitionsRequisitionIdRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/settings/': {
      id: '/_authed/hiring/settings/'
      path: '/settings'
      fullPath: '/hiring/settings/'
      preLoaderRoute: typeof HiringSettingsIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/people/employees/': {
      id: '/_authed/people/employees/'
      path: '/employees'
      fullPath: '/people/employees/'
      preLoaderRoute: typeof PeopleEmployeesIndexRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/employees/$workerId': {
      id: '/_authed/people/employees/$workerId'
      path: '/employees/$workerId'
      fullPath: '/people/employees/$workerId'
      preLoaderRoute: typeof PeopleEmployeesWorkerIdRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/people/performance/': {
      id: '/_authed/people/performance/'
      path: '/'
      fullPath: '/people/performance/'
      preLoaderRoute: typeof PeoplePerformanceIndexRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/audit': {
      id: '/_authed/people/performance/audit'
      path: '/audit'
      fullPath: '/people/performance/audit'
      preLoaderRoute: typeof PeoplePerformanceAuditRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/configuration': {
      id: '/_authed/people/performance/configuration'
      path: '/configuration'
      fullPath: '/people/performance/configuration'
      preLoaderRoute: typeof PeoplePerformanceConfigurationRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/cycle': {
      id: '/_authed/people/performance/cycle'
      path: '/cycle'
      fullPath: '/people/performance/cycle'
      preLoaderRoute: typeof PeoplePerformanceCycleRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/history': {
      id: '/_authed/people/performance/history'
      path: '/history'
      fullPath: '/people/performance/history'
      preLoaderRoute: typeof PeoplePerformanceHistoryRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/morale': {
      id: '/_authed/people/performance/morale'
      path: '/morale'
      fullPath: '/people/performance/morale'
      preLoaderRoute: typeof PeoplePerformanceMoraleRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/scoring': {
      id: '/_authed/people/performance/scoring'
      path: '/scoring'
      fullPath: '/people/performance/scoring'
      preLoaderRoute: typeof PeoplePerformanceScoringRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/people/performance/self-assessment': {
      id: '/_authed/people/performance/self-assessment'
      path: '/self-assessment'
      fullPath: '/people/performance/self-assessment'
      preLoaderRoute: typeof PeoplePerformanceSelfAssessmentRouteImport
      parentRoute: typeof PeoplePerformanceRouteRoute
    }
    '/_authed/planner/groups_/$groupId': {
      id: '/_authed/planner/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/planner/groups/$groupId'
      preLoaderRoute: typeof PlannerGroupsGroupIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/groups_/discover': {
      id: '/_authed/planner/groups_/discover'
      path: '/groups/discover'
      fullPath: '/planner/groups/discover'
      preLoaderRoute: typeof PlannerGroupsDiscoverRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/plans_/$planId': {
      id: '/_authed/planner/plans_/$planId'
      path: '/plans/$planId'
      fullPath: '/planner/plans/$planId'
      preLoaderRoute: typeof PlannerPlansPlanIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/pm/accounts/': {
      id: '/_authed/pm/accounts/'
      path: '/accounts'
      fullPath: '/pm/accounts/'
      preLoaderRoute: typeof PmAccountsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/accounts/$accountId': {
      id: '/_authed/pm/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/pm/accounts/$accountId'
      preLoaderRoute: typeof PmAccountsAccountIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/metrics/': {
      id: '/_authed/pm/metrics/'
      path: '/metrics'
      fullPath: '/pm/metrics/'
      preLoaderRoute: typeof PmMetricsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/projects/': {
      id: '/_authed/pm/projects/'
      path: '/projects'
      fullPath: '/pm/projects/'
      preLoaderRoute: typeof PmProjectsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/projects/$projectId': {
      id: '/_authed/pm/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/pm/projects/$projectId'
      preLoaderRoute: typeof PmProjectsProjectIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/requests/': {
      id: '/_authed/pm/requests/'
      path: '/requests'
      fullPath: '/pm/requests/'
      preLoaderRoute: typeof PmRequestsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/requests/$charterId': {
      id: '/_authed/pm/requests/$charterId'
      path: '/requests/$charterId'
      fullPath: '/pm/requests/$charterId'
      preLoaderRoute: typeof PmRequestsCharterIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/resourcing/': {
      id: '/_authed/pm/resourcing/'
      path: '/resourcing'
      fullPath: '/pm/resourcing/'
      preLoaderRoute: typeof PmResourcingIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/risks/': {
      id: '/_authed/pm/risks/'
      path: '/risks'
      fullPath: '/pm/risks/'
      preLoaderRoute: typeof PmRisksIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/weekly/': {
      id: '/_authed/pm/weekly/'
      path: '/weekly'
      fullPath: '/pm/weekly/'
      preLoaderRoute: typeof PmWeeklyIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/agent/workflows/runs/$runId': {
      id: '/_authed/agent/workflows/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/agent/workflows/runs/$runId'
      preLoaderRoute: typeof AgentWorkflowsRunsRunIdRouteImport
      parentRoute: typeof AgentWorkflowsRouteRoute
    }
    '/_authed/planner/plans_/$planId_/settings_/categories': {
      id: '/_authed/planner/plans_/$planId_/settings_/categories'
      path: '/plans/$planId/settings/categories'
      fullPath: '/planner/plans/$planId/settings/categories'
      preLoaderRoute: typeof PlannerPlansPlanIdSettingsCategoriesRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/plans_/$planId_/tasks_/$taskId': {
      id: '/_authed/planner/plans_/$planId_/tasks_/$taskId'
      path: '/plans/$planId/tasks/$taskId'
      fullPath: '/planner/plans/$planId/tasks/$taskId'
      preLoaderRoute: typeof PlannerPlansPlanIdTasksTaskIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminM365DirectoryRoute: typeof AdminM365DirectoryRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRoleAccessRoute: typeof AdminRoleAccessRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminSsoRoute: typeof AdminSsoRoute
  AdminTenantRoute: typeof AdminTenantRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminM365DirectoryRoute: AdminM365DirectoryRoute,
  AdminMailRoute: AdminMailRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRoleAccessRoute: AdminRoleAccessRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminSsoRoute: AdminSsoRoute,
  AdminTenantRoute: AdminTenantRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgentWorkflowsRouteRouteChildren {
  AgentWorkflowsIndexRoute: typeof AgentWorkflowsIndexRoute
  AgentWorkflowsRunsRunIdRoute: typeof AgentWorkflowsRunsRunIdRoute
}

const AgentWorkflowsRouteRouteChildren: AgentWorkflowsRouteRouteChildren = {
  AgentWorkflowsIndexRoute: AgentWorkflowsIndexRoute,
  AgentWorkflowsRunsRunIdRoute: AgentWorkflowsRunsRunIdRoute,
}

const AgentWorkflowsRouteRouteWithChildren =
  AgentWorkflowsRouteRoute._addFileChildren(AgentWorkflowsRouteRouteChildren)

interface AgentRouteRouteChildren {
  AgentWorkflowsRouteRoute: typeof AgentWorkflowsRouteRouteWithChildren
  AgentChatRoute: typeof AgentChatRoute
  AgentKnowledgeRoute: typeof AgentKnowledgeRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentWorkflowsRouteRoute: AgentWorkflowsRouteRouteWithChildren,
  AgentChatRoute: AgentChatRoute,
  AgentKnowledgeRoute: AgentKnowledgeRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

interface HiringRouteRouteChildren {
  HiringIndexRoute: typeof HiringIndexRoute
  HiringRequisitionsRequisitionIdRoute: typeof HiringRequisitionsRequisitionIdRoute
  HiringCandidatesIndexRoute: typeof HiringCandidatesIndexRoute
  HiringInterviewsIndexRoute: typeof HiringInterviewsIndexRoute
  HiringKnowledgeIndexRoute: typeof HiringKnowledgeIndexRoute
  HiringRequisitionsIndexRoute: typeof HiringRequisitionsIndexRoute
  HiringSettingsIndexRoute: typeof HiringSettingsIndexRoute
}

const HiringRouteRouteChildren: HiringRouteRouteChildren = {
  HiringIndexRoute: HiringIndexRoute,
  HiringRequisitionsRequisitionIdRoute: HiringRequisitionsRequisitionIdRoute,
  HiringCandidatesIndexRoute: HiringCandidatesIndexRoute,
  HiringInterviewsIndexRoute: HiringInterviewsIndexRoute,
  HiringKnowledgeIndexRoute: HiringKnowledgeIndexRoute,
  HiringRequisitionsIndexRoute: HiringRequisitionsIndexRoute,
  HiringSettingsIndexRoute: HiringSettingsIndexRoute,
}

const HiringRouteRouteWithChildren = HiringRouteRoute._addFileChildren(
  HiringRouteRouteChildren,
)

interface PeoplePerformanceRouteRouteChildren {
  PeoplePerformanceAuditRoute: typeof PeoplePerformanceAuditRoute
  PeoplePerformanceConfigurationRoute: typeof PeoplePerformanceConfigurationRoute
  PeoplePerformanceCycleRoute: typeof PeoplePerformanceCycleRoute
  PeoplePerformanceHistoryRoute: typeof PeoplePerformanceHistoryRoute
  PeoplePerformanceMoraleRoute: typeof PeoplePerformanceMoraleRoute
  PeoplePerformanceScoringRoute: typeof PeoplePerformanceScoringRoute
  PeoplePerformanceSelfAssessmentRoute: typeof PeoplePerformanceSelfAssessmentRoute
  PeoplePerformanceIndexRoute: typeof PeoplePerformanceIndexRoute
}

const PeoplePerformanceRouteRouteChildren: PeoplePerformanceRouteRouteChildren =
  {
    PeoplePerformanceAuditRoute: PeoplePerformanceAuditRoute,
    PeoplePerformanceConfigurationRoute: PeoplePerformanceConfigurationRoute,
    PeoplePerformanceCycleRoute: PeoplePerformanceCycleRoute,
    PeoplePerformanceHistoryRoute: PeoplePerformanceHistoryRoute,
    PeoplePerformanceMoraleRoute: PeoplePerformanceMoraleRoute,
    PeoplePerformanceScoringRoute: PeoplePerformanceScoringRoute,
    PeoplePerformanceSelfAssessmentRoute: PeoplePerformanceSelfAssessmentRoute,
    PeoplePerformanceIndexRoute: PeoplePerformanceIndexRoute,
  }

const PeoplePerformanceRouteRouteWithChildren =
  PeoplePerformanceRouteRoute._addFileChildren(
    PeoplePerformanceRouteRouteChildren,
  )

interface PeopleRouteRouteChildren {
  PeoplePerformanceRouteRoute: typeof PeoplePerformanceRouteRouteWithChildren
  PeopleAllocationRoute: typeof PeopleAllocationRoute
  PeopleOffboardingRoute: typeof PeopleOffboardingRoute
  PeopleOnboardingRoute: typeof PeopleOnboardingRoute
  PeopleOrgRoute: typeof PeopleOrgRoute
  PeopleProbationRoute: typeof PeopleProbationRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PeopleEmployeesWorkerIdRoute: typeof PeopleEmployeesWorkerIdRoute
  PeopleEmployeesIndexRoute: typeof PeopleEmployeesIndexRoute
}

const PeopleRouteRouteChildren: PeopleRouteRouteChildren = {
  PeoplePerformanceRouteRoute: PeoplePerformanceRouteRouteWithChildren,
  PeopleAllocationRoute: PeopleAllocationRoute,
  PeopleOffboardingRoute: PeopleOffboardingRoute,
  PeopleOnboardingRoute: PeopleOnboardingRoute,
  PeopleOrgRoute: PeopleOrgRoute,
  PeopleProbationRoute: PeopleProbationRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PeopleEmployeesWorkerIdRoute: PeopleEmployeesWorkerIdRoute,
  PeopleEmployeesIndexRoute: PeopleEmployeesIndexRoute,
}

const PeopleRouteRouteWithChildren = PeopleRouteRoute._addFileChildren(
  PeopleRouteRouteChildren,
)

interface PlannerRouteRouteChildren {
  PlannerGroupsRoute: typeof PlannerGroupsRoute
  PlannerMyTasksRoute: typeof PlannerMyTasksRoute
  PlannerTrashRoute: typeof PlannerTrashRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  PlannerGroupsGroupIdRoute: typeof PlannerGroupsGroupIdRoute
  PlannerGroupsDiscoverRoute: typeof PlannerGroupsDiscoverRoute
  PlannerPlansPlanIdRoute: typeof PlannerPlansPlanIdRoute
  PlannerPlansPlanIdSettingsCategoriesRoute: typeof PlannerPlansPlanIdSettingsCategoriesRoute
  PlannerPlansPlanIdTasksTaskIdRoute: typeof PlannerPlansPlanIdTasksTaskIdRoute
}

const PlannerRouteRouteChildren: PlannerRouteRouteChildren = {
  PlannerGroupsRoute: PlannerGroupsRoute,
  PlannerMyTasksRoute: PlannerMyTasksRoute,
  PlannerTrashRoute: PlannerTrashRoute,
  PlannerIndexRoute: PlannerIndexRoute,
  PlannerGroupsGroupIdRoute: PlannerGroupsGroupIdRoute,
  PlannerGroupsDiscoverRoute: PlannerGroupsDiscoverRoute,
  PlannerPlansPlanIdRoute: PlannerPlansPlanIdRoute,
  PlannerPlansPlanIdSettingsCategoriesRoute:
    PlannerPlansPlanIdSettingsCategoriesRoute,
  PlannerPlansPlanIdTasksTaskIdRoute: PlannerPlansPlanIdTasksTaskIdRoute,
}

const PlannerRouteRouteWithChildren = PlannerRouteRoute._addFileChildren(
  PlannerRouteRouteChildren,
)

interface PmRouteRouteChildren {
  PmIndexRoute: typeof PmIndexRoute
  PmAccountsAccountIdRoute: typeof PmAccountsAccountIdRoute
  PmProjectsProjectIdRoute: typeof PmProjectsProjectIdRoute
  PmRequestsCharterIdRoute: typeof PmRequestsCharterIdRoute
  PmAccountsIndexRoute: typeof PmAccountsIndexRoute
  PmMetricsIndexRoute: typeof PmMetricsIndexRoute
  PmProjectsIndexRoute: typeof PmProjectsIndexRoute
  PmRequestsIndexRoute: typeof PmRequestsIndexRoute
  PmResourcingIndexRoute: typeof PmResourcingIndexRoute
  PmRisksIndexRoute: typeof PmRisksIndexRoute
  PmWeeklyIndexRoute: typeof PmWeeklyIndexRoute
}

const PmRouteRouteChildren: PmRouteRouteChildren = {
  PmIndexRoute: PmIndexRoute,
  PmAccountsAccountIdRoute: PmAccountsAccountIdRoute,
  PmProjectsProjectIdRoute: PmProjectsProjectIdRoute,
  PmRequestsCharterIdRoute: PmRequestsCharterIdRoute,
  PmAccountsIndexRoute: PmAccountsIndexRoute,
  PmMetricsIndexRoute: PmMetricsIndexRoute,
  PmProjectsIndexRoute: PmProjectsIndexRoute,
  PmRequestsIndexRoute: PmRequestsIndexRoute,
  PmResourcingIndexRoute: PmResourcingIndexRoute,
  PmRisksIndexRoute: PmRisksIndexRoute,
  PmWeeklyIndexRoute: PmWeeklyIndexRoute,
}

const PmRouteRouteWithChildren =
  PmRouteRoute._addFileChildren(PmRouteRouteChildren)

interface routesAuthedRouteRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  HiringRouteRoute: typeof HiringRouteRouteWithChildren
  PeopleRouteRoute: typeof PeopleRouteRouteWithChildren
  PlannerRouteRoute: typeof PlannerRouteRouteWithChildren
  PmRouteRoute: typeof PmRouteRouteWithChildren
  routesAuthedIndexRoute: typeof routesAuthedIndexRoute
  routesAuthedSettingsIndexRoute: typeof routesAuthedSettingsIndexRoute
  routesAuthedSettingsAvailabilityRoute: typeof routesAuthedSettingsAvailabilityRoute
  routesAuthedSettingsNotificationsRoute: typeof routesAuthedSettingsNotificationsRoute
  routesAuthedSettingsProfileRoute: typeof routesAuthedSettingsProfileRoute
  routesAuthedSettingsRolesRoute: typeof routesAuthedSettingsRolesRoute
  routesAuthedSettingsSecurityRoute: typeof routesAuthedSettingsSecurityRoute
  routesAuthedSettingsSkillsRoute: typeof routesAuthedSettingsSkillsRoute
}

const routesAuthedRouteRouteChildren: routesAuthedRouteRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  HiringRouteRoute: HiringRouteRouteWithChildren,
  PeopleRouteRoute: PeopleRouteRouteWithChildren,
  PlannerRouteRoute: PlannerRouteRouteWithChildren,
  PmRouteRoute: PmRouteRouteWithChildren,
  routesAuthedIndexRoute: routesAuthedIndexRoute,
  routesAuthedSettingsIndexRoute: routesAuthedSettingsIndexRoute,
  routesAuthedSettingsAvailabilityRoute: routesAuthedSettingsAvailabilityRoute,
  routesAuthedSettingsNotificationsRoute:
    routesAuthedSettingsNotificationsRoute,
  routesAuthedSettingsProfileRoute: routesAuthedSettingsProfileRoute,
  routesAuthedSettingsRolesRoute: routesAuthedSettingsRolesRoute,
  routesAuthedSettingsSecurityRoute: routesAuthedSettingsSecurityRoute,
  routesAuthedSettingsSkillsRoute: routesAuthedSettingsSkillsRoute,
}

const routesAuthedRouteRouteWithChildren =
  routesAuthedRouteRoute._addFileChildren(routesAuthedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  routesAuthedRouteRoute: routesAuthedRouteRouteWithChildren,
  routes403Route: routes403Route,
  routesLoginRoute: routesLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
