/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as routesLoginRouteImport } from './routes/login'
import { Route as routes403RouteImport } from './routes/403'
import { Route as routesAuthedRouteRouteImport } from './routes/_authed/route'
import { Route as routesAuthedIndexRouteImport } from './routes/_authed/index'
import { Route as DevDatatableRouteImport } from './routes/dev/datatable'
import { Route as routesAuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as PmRouteRouteImport } from './../../../packages/web-pm/src/routes/route'
import { Route as PlannerRouteRouteImport } from './../../../packages/web-planner/src/routes/route'
import { Route as PeopleRouteRouteImport } from './../../../packages/web-people/src/routes/route'
import { Route as HiringRouteRouteImport } from './../../../packages/web-hiring/src/routes/route'
import { Route as AgentRouteRouteImport } from './../../../packages/web-agent/src/routes/route'
import { Route as AdminRouteRouteImport } from './../../../packages/web-admin/src/routes/route'
import { Route as PmIndexRouteImport } from './../../../packages/web-pm/src/routes/index'
import { Route as PlannerIndexRouteImport } from './../../../packages/web-planner/src/routes/index'
import { Route as PeopleIndexRouteImport } from './../../../packages/web-people/src/routes/index'
import { Route as HiringIndexRouteImport } from './../../../packages/web-hiring/src/routes/index'
import { Route as AgentIndexRouteImport } from './../../../packages/web-agent/src/routes/index'
import { Route as AdminIndexRouteImport } from './../../../packages/web-admin/src/routes/index'
import { Route as PlannerTrashRouteImport } from './../../../packages/web-planner/src/routes/trash'
import { Route as PlannerMyTasksRouteImport } from './../../../packages/web-planner/src/routes/my-tasks'
import { Route as PlannerGroupsRouteImport } from './../../../packages/web-planner/src/routes/groups'
import { Route as PeopleWorkerIdRouteImport } from './../../../packages/web-people/src/routes/$workerId'
import { Route as AgentKnowledgeRouteImport } from './../../../packages/web-agent/src/routes/knowledge'
import { Route as AgentChatRouteImport } from './../../../packages/web-agent/src/routes/chat'
import { Route as AdminTenantRouteImport } from './../../../packages/web-admin/src/routes/tenant'
import { Route as AdminSsoRouteImport } from './../../../packages/web-admin/src/routes/sso'
import { Route as AdminSkillsRouteImport } from './../../../packages/web-admin/src/routes/skills'
import { Route as AdminRoleAccessRouteImport } from './../../../packages/web-admin/src/routes/role-access'
import { Route as AdminNotificationsRouteImport } from './../../../packages/web-admin/src/routes/notifications'
import { Route as AdminMailRouteImport } from './../../../packages/web-admin/src/routes/mail'
import { Route as AdminAuditRouteImport } from './../../../packages/web-admin/src/routes/audit'
import { Route as AgentWorkflowsRouteRouteImport } from './../../../packages/web-agent/src/routes/workflows/route'
import { Route as PmRequestsIndexRouteImport } from './../../../packages/web-pm/src/routes/requests/index'
import { Route as PmProjectsIndexRouteImport } from './../../../packages/web-pm/src/routes/projects/index'
import { Route as PmAccountsIndexRouteImport } from './../../../packages/web-pm/src/routes/accounts/index'
import { Route as HiringSettingsIndexRouteImport } from './../../../packages/web-hiring/src/routes/settings/index'
import { Route as HiringRequisitionsIndexRouteImport } from './../../../packages/web-hiring/src/routes/requisitions/index'
import { Route as HiringCandidatesIndexRouteImport } from './../../../packages/web-hiring/src/routes/candidates/index'
import { Route as AgentWorkflowsIndexRouteImport } from './../../../packages/web-agent/src/routes/workflows/index'
import { Route as PmRequestsCharterIdRouteImport } from './../../../packages/web-pm/src/routes/requests/$charterId'
import { Route as PmProjectsProjectIdRouteImport } from './../../../packages/web-pm/src/routes/projects/$projectId'
import { Route as PmAccountsAccountIdRouteImport } from './../../../packages/web-pm/src/routes/accounts/$accountId'
import { Route as PlannerPlansPlanIdRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId'
import { Route as PlannerGroupsDiscoverRouteImport } from './../../../packages/web-planner/src/routes/groups_/discover'
import { Route as PlannerGroupsGroupIdRouteImport } from './../../../packages/web-planner/src/routes/groups_/$groupId'
import { Route as HiringRequisitionsRequisitionIdRouteImport } from './../../../packages/web-hiring/src/routes/requisitions/$requisitionId'
import { Route as AgentWorkflowsRunsRunIdRouteImport } from './../../../packages/web-agent/src/routes/workflows/runs/$runId'
import { Route as PlannerPlansPlanIdTasksTaskIdRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId_/tasks_/$taskId'
import { Route as PlannerPlansPlanIdSettingsCategoriesRouteImport } from './../../../packages/web-planner/src/routes/plans_/$planId_/settings_/categories'

const routesLoginRoute = routesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const routes403Route = routes403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const routesAuthedRouteRoute = routesAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const routesAuthedIndexRoute = routesAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const DevDatatableRoute = DevDatatableRouteImport.update({
  id: '/dev/datatable',
  path: '/dev/datatable',
  getParentRoute: () => rootRouteImport,
} as any)
const routesAuthedProfileRoute = routesAuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PmRouteRoute = PmRouteRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PlannerRouteRoute = PlannerRouteRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PeopleRouteRoute = PeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const HiringRouteRoute = HiringRouteRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => routesAuthedRouteRoute,
} as any)
const PmIndexRoute = PmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const HiringIndexRoute = HiringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PlannerTrashRoute = PlannerTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerMyTasksRoute = PlannerMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerGroupsRoute = PlannerGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PeopleWorkerIdRoute = PeopleWorkerIdRouteImport.update({
  id: '/$workerId',
  path: '/$workerId',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const AgentKnowledgeRoute = AgentKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AdminTenantRoute = AdminTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSsoRoute = AdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleAccessRoute = AdminRoleAccessRouteImport.update({
  id: '/role-access',
  path: '/role-access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AgentWorkflowsRouteRoute = AgentWorkflowsRouteRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AgentRouteRoute,
} as any)
const PmRequestsIndexRoute = PmRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmProjectsIndexRoute = PmProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmAccountsIndexRoute = PmAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => PmRouteRoute,
} as any)
const HiringSettingsIndexRoute = HiringSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringRequisitionsIndexRoute = HiringRequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const HiringCandidatesIndexRoute = HiringCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => HiringRouteRoute,
} as any)
const AgentWorkflowsIndexRoute = AgentWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentWorkflowsRouteRoute,
} as any)
const PmRequestsCharterIdRoute = PmRequestsCharterIdRouteImport.update({
  id: '/requests/$charterId',
  path: '/requests/$charterId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmProjectsProjectIdRoute = PmProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmAccountsAccountIdRoute = PmAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => PmRouteRoute,
} as any)
const PlannerPlansPlanIdRoute = PlannerPlansPlanIdRouteImport.update({
  id: '/plans_/$planId',
  path: '/plans/$planId',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerGroupsDiscoverRoute = PlannerGroupsDiscoverRouteImport.update({
  id: '/groups_/discover',
  path: '/groups/discover',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const PlannerGroupsGroupIdRoute = PlannerGroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => PlannerRouteRoute,
} as any)
const HiringRequisitionsRequisitionIdRoute =
  HiringRequisitionsRequisitionIdRouteImport.update({
    id: '/requisitions/$requisitionId',
    path: '/requisitions/$requisitionId',
    getParentRoute: () => HiringRouteRoute,
  } as any)
const AgentWorkflowsRunsRunIdRoute = AgentWorkflowsRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AgentWorkflowsRouteRoute,
} as any)
const PlannerPlansPlanIdTasksTaskIdRoute =
  PlannerPlansPlanIdTasksTaskIdRouteImport.update({
    id: '/plans_/$planId_/tasks_/$taskId',
    path: '/plans/$planId/tasks/$taskId',
    getParentRoute: () => PlannerRouteRoute,
  } as any)
const PlannerPlansPlanIdSettingsCategoriesRoute =
  PlannerPlansPlanIdSettingsCategoriesRouteImport.update({
    id: '/plans_/$planId_/settings_/categories',
    path: '/plans/$planId/settings/categories',
    getParentRoute: () => PlannerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof routesAuthedIndexRoute
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/hiring': typeof HiringRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/planner': typeof PlannerRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/profile': typeof routesAuthedProfileRoute
  '/dev/datatable': typeof DevDatatableRoute
  '/agent/workflows': typeof AgentWorkflowsRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/role-access': typeof AdminRoleAccessRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/people/$workerId': typeof PeopleWorkerIdRoute
  '/planner/groups': typeof PlannerGroupsRoute
  '/planner/my-tasks': typeof PlannerMyTasksRoute
  '/planner/trash': typeof PlannerTrashRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/hiring/': typeof HiringIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/pm/': typeof PmIndexRoute
  '/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/planner/groups/$groupId': typeof PlannerGroupsGroupIdRoute
  '/planner/groups/discover': typeof PlannerGroupsDiscoverRoute
  '/planner/plans/$planId': typeof PlannerPlansPlanIdRoute
  '/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/agent/workflows/': typeof AgentWorkflowsIndexRoute
  '/hiring/candidates/': typeof HiringCandidatesIndexRoute
  '/hiring/requisitions/': typeof HiringRequisitionsIndexRoute
  '/hiring/settings/': typeof HiringSettingsIndexRoute
  '/pm/accounts/': typeof PmAccountsIndexRoute
  '/pm/projects/': typeof PmProjectsIndexRoute
  '/pm/requests/': typeof PmRequestsIndexRoute
  '/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/planner/plans/$planId/settings/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/planner/plans/$planId/tasks/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/profile': typeof routesAuthedProfileRoute
  '/dev/datatable': typeof DevDatatableRoute
  '/': typeof routesAuthedIndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/role-access': typeof AdminRoleAccessRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/people/$workerId': typeof PeopleWorkerIdRoute
  '/planner/groups': typeof PlannerGroupsRoute
  '/planner/my-tasks': typeof PlannerMyTasksRoute
  '/planner/trash': typeof PlannerTrashRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/hiring': typeof HiringIndexRoute
  '/people': typeof PeopleIndexRoute
  '/planner': typeof PlannerIndexRoute
  '/pm': typeof PmIndexRoute
  '/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/planner/groups/$groupId': typeof PlannerGroupsGroupIdRoute
  '/planner/groups/discover': typeof PlannerGroupsDiscoverRoute
  '/planner/plans/$planId': typeof PlannerPlansPlanIdRoute
  '/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/agent/workflows': typeof AgentWorkflowsIndexRoute
  '/hiring/candidates': typeof HiringCandidatesIndexRoute
  '/hiring/requisitions': typeof HiringRequisitionsIndexRoute
  '/hiring/settings': typeof HiringSettingsIndexRoute
  '/pm/accounts': typeof PmAccountsIndexRoute
  '/pm/projects': typeof PmProjectsIndexRoute
  '/pm/requests': typeof PmRequestsIndexRoute
  '/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/planner/plans/$planId/settings/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/planner/plans/$planId/tasks/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof routesAuthedRouteRouteWithChildren
  '/403': typeof routes403Route
  '/login': typeof routesLoginRoute
  '/_authed/admin': typeof AdminRouteRouteWithChildren
  '/_authed/agent': typeof AgentRouteRouteWithChildren
  '/_authed/hiring': typeof HiringRouteRouteWithChildren
  '/_authed/people': typeof PeopleRouteRouteWithChildren
  '/_authed/planner': typeof PlannerRouteRouteWithChildren
  '/_authed/pm': typeof PmRouteRouteWithChildren
  '/_authed/profile': typeof routesAuthedProfileRoute
  '/dev/datatable': typeof DevDatatableRoute
  '/_authed/': typeof routesAuthedIndexRoute
  '/_authed/agent/workflows': typeof AgentWorkflowsRouteRouteWithChildren
  '/_authed/admin/audit': typeof AdminAuditRoute
  '/_authed/admin/mail': typeof AdminMailRoute
  '/_authed/admin/notifications': typeof AdminNotificationsRoute
  '/_authed/admin/role-access': typeof AdminRoleAccessRoute
  '/_authed/admin/skills': typeof AdminSkillsRoute
  '/_authed/admin/sso': typeof AdminSsoRoute
  '/_authed/admin/tenant': typeof AdminTenantRoute
  '/_authed/agent/chat': typeof AgentChatRoute
  '/_authed/agent/knowledge': typeof AgentKnowledgeRoute
  '/_authed/people/$workerId': typeof PeopleWorkerIdRoute
  '/_authed/planner/groups': typeof PlannerGroupsRoute
  '/_authed/planner/my-tasks': typeof PlannerMyTasksRoute
  '/_authed/planner/trash': typeof PlannerTrashRoute
  '/_authed/admin/': typeof AdminIndexRoute
  '/_authed/agent/': typeof AgentIndexRoute
  '/_authed/hiring/': typeof HiringIndexRoute
  '/_authed/people/': typeof PeopleIndexRoute
  '/_authed/planner/': typeof PlannerIndexRoute
  '/_authed/pm/': typeof PmIndexRoute
  '/_authed/hiring/requisitions/$requisitionId': typeof HiringRequisitionsRequisitionIdRoute
  '/_authed/planner/groups_/$groupId': typeof PlannerGroupsGroupIdRoute
  '/_authed/planner/groups_/discover': typeof PlannerGroupsDiscoverRoute
  '/_authed/planner/plans_/$planId': typeof PlannerPlansPlanIdRoute
  '/_authed/pm/accounts/$accountId': typeof PmAccountsAccountIdRoute
  '/_authed/pm/projects/$projectId': typeof PmProjectsProjectIdRoute
  '/_authed/pm/requests/$charterId': typeof PmRequestsCharterIdRoute
  '/_authed/agent/workflows/': typeof AgentWorkflowsIndexRoute
  '/_authed/hiring/candidates/': typeof HiringCandidatesIndexRoute
  '/_authed/hiring/requisitions/': typeof HiringRequisitionsIndexRoute
  '/_authed/hiring/settings/': typeof HiringSettingsIndexRoute
  '/_authed/pm/accounts/': typeof PmAccountsIndexRoute
  '/_authed/pm/projects/': typeof PmProjectsIndexRoute
  '/_authed/pm/requests/': typeof PmRequestsIndexRoute
  '/_authed/agent/workflows/runs/$runId': typeof AgentWorkflowsRunsRunIdRoute
  '/_authed/planner/plans_/$planId_/settings_/categories': typeof PlannerPlansPlanIdSettingsCategoriesRoute
  '/_authed/planner/plans_/$planId_/tasks_/$taskId': typeof PlannerPlansPlanIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/admin'
    | '/agent'
    | '/hiring'
    | '/people'
    | '/planner'
    | '/pm'
    | '/profile'
    | '/dev/datatable'
    | '/agent/workflows'
    | '/admin/audit'
    | '/admin/mail'
    | '/admin/notifications'
    | '/admin/role-access'
    | '/admin/skills'
    | '/admin/sso'
    | '/admin/tenant'
    | '/agent/chat'
    | '/agent/knowledge'
    | '/people/$workerId'
    | '/planner/groups'
    | '/planner/my-tasks'
    | '/planner/trash'
    | '/admin/'
    | '/agent/'
    | '/hiring/'
    | '/people/'
    | '/planner/'
    | '/pm/'
    | '/hiring/requisitions/$requisitionId'
    | '/planner/groups/$groupId'
    | '/planner/groups/discover'
    | '/planner/plans/$planId'
    | '/pm/accounts/$accountId'
    | '/pm/projects/$projectId'
    | '/pm/requests/$charterId'
    | '/agent/workflows/'
    | '/hiring/candidates/'
    | '/hiring/requisitions/'
    | '/hiring/settings/'
    | '/pm/accounts/'
    | '/pm/projects/'
    | '/pm/requests/'
    | '/agent/workflows/runs/$runId'
    | '/planner/plans/$planId/settings/categories'
    | '/planner/plans/$planId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/profile'
    | '/dev/datatable'
    | '/'
    | '/admin/audit'
    | '/admin/mail'
    | '/admin/notifications'
    | '/admin/role-access'
    | '/admin/skills'
    | '/admin/sso'
    | '/admin/tenant'
    | '/agent/chat'
    | '/agent/knowledge'
    | '/people/$workerId'
    | '/planner/groups'
    | '/planner/my-tasks'
    | '/planner/trash'
    | '/admin'
    | '/agent'
    | '/hiring'
    | '/people'
    | '/planner'
    | '/pm'
    | '/hiring/requisitions/$requisitionId'
    | '/planner/groups/$groupId'
    | '/planner/groups/discover'
    | '/planner/plans/$planId'
    | '/pm/accounts/$accountId'
    | '/pm/projects/$projectId'
    | '/pm/requests/$charterId'
    | '/agent/workflows'
    | '/hiring/candidates'
    | '/hiring/requisitions'
    | '/hiring/settings'
    | '/pm/accounts'
    | '/pm/projects'
    | '/pm/requests'
    | '/agent/workflows/runs/$runId'
    | '/planner/plans/$planId/settings/categories'
    | '/planner/plans/$planId/tasks/$taskId'
  id:
    | '__root__'
    | '/_authed'
    | '/403'
    | '/login'
    | '/_authed/admin'
    | '/_authed/agent'
    | '/_authed/hiring'
    | '/_authed/people'
    | '/_authed/planner'
    | '/_authed/pm'
    | '/_authed/profile'
    | '/dev/datatable'
    | '/_authed/'
    | '/_authed/agent/workflows'
    | '/_authed/admin/audit'
    | '/_authed/admin/mail'
    | '/_authed/admin/notifications'
    | '/_authed/admin/role-access'
    | '/_authed/admin/skills'
    | '/_authed/admin/sso'
    | '/_authed/admin/tenant'
    | '/_authed/agent/chat'
    | '/_authed/agent/knowledge'
    | '/_authed/people/$workerId'
    | '/_authed/planner/groups'
    | '/_authed/planner/my-tasks'
    | '/_authed/planner/trash'
    | '/_authed/admin/'
    | '/_authed/agent/'
    | '/_authed/hiring/'
    | '/_authed/people/'
    | '/_authed/planner/'
    | '/_authed/pm/'
    | '/_authed/hiring/requisitions/$requisitionId'
    | '/_authed/planner/groups_/$groupId'
    | '/_authed/planner/groups_/discover'
    | '/_authed/planner/plans_/$planId'
    | '/_authed/pm/accounts/$accountId'
    | '/_authed/pm/projects/$projectId'
    | '/_authed/pm/requests/$charterId'
    | '/_authed/agent/workflows/'
    | '/_authed/hiring/candidates/'
    | '/_authed/hiring/requisitions/'
    | '/_authed/hiring/settings/'
    | '/_authed/pm/accounts/'
    | '/_authed/pm/projects/'
    | '/_authed/pm/requests/'
    | '/_authed/agent/workflows/runs/$runId'
    | '/_authed/planner/plans_/$planId_/settings_/categories'
    | '/_authed/planner/plans_/$planId_/tasks_/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  routesAuthedRouteRoute: typeof routesAuthedRouteRouteWithChildren
  routes403Route: typeof routes403Route
  routesLoginRoute: typeof routesLoginRoute
  DevDatatableRoute: typeof DevDatatableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof routesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof routes403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routesAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof routesAuthedIndexRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/dev/datatable': {
      id: '/dev/datatable'
      path: '/dev/datatable'
      fullPath: '/dev/datatable'
      preLoaderRoute: typeof DevDatatableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof routesAuthedProfileRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/pm': {
      id: '/_authed/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/planner': {
      id: '/_authed/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/hiring': {
      id: '/_authed/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/agent': {
      id: '/_authed/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof routesAuthedRouteRoute
    }
    '/_authed/pm/': {
      id: '/_authed/pm/'
      path: '/'
      fullPath: '/pm/'
      preLoaderRoute: typeof PmIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/planner/': {
      id: '/_authed/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/hiring/': {
      id: '/_authed/hiring/'
      path: '/'
      fullPath: '/hiring/'
      preLoaderRoute: typeof HiringIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/agent/': {
      id: '/_authed/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/planner/trash': {
      id: '/_authed/planner/trash'
      path: '/trash'
      fullPath: '/planner/trash'
      preLoaderRoute: typeof PlannerTrashRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/my-tasks': {
      id: '/_authed/planner/my-tasks'
      path: '/my-tasks'
      fullPath: '/planner/my-tasks'
      preLoaderRoute: typeof PlannerMyTasksRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/groups': {
      id: '/_authed/planner/groups'
      path: '/groups'
      fullPath: '/planner/groups'
      preLoaderRoute: typeof PlannerGroupsRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/people/$workerId': {
      id: '/_authed/people/$workerId'
      path: '/$workerId'
      fullPath: '/people/$workerId'
      preLoaderRoute: typeof PeopleWorkerIdRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/_authed/agent/knowledge': {
      id: '/_authed/agent/knowledge'
      path: '/knowledge'
      fullPath: '/agent/knowledge'
      preLoaderRoute: typeof AgentKnowledgeRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/agent/chat': {
      id: '/_authed/agent/chat'
      path: '/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/admin/tenant': {
      id: '/_authed/admin/tenant'
      path: '/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AdminTenantRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/sso': {
      id: '/_authed/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AdminSsoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/skills': {
      id: '/_authed/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/role-access': {
      id: '/_authed/admin/role-access'
      path: '/role-access'
      fullPath: '/admin/role-access'
      preLoaderRoute: typeof AdminRoleAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/notifications': {
      id: '/_authed/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/mail': {
      id: '/_authed/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/agent/workflows': {
      id: '/_authed/agent/workflows'
      path: '/workflows'
      fullPath: '/agent/workflows'
      preLoaderRoute: typeof AgentWorkflowsRouteRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/_authed/pm/requests/': {
      id: '/_authed/pm/requests/'
      path: '/requests'
      fullPath: '/pm/requests/'
      preLoaderRoute: typeof PmRequestsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/projects/': {
      id: '/_authed/pm/projects/'
      path: '/projects'
      fullPath: '/pm/projects/'
      preLoaderRoute: typeof PmProjectsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/accounts/': {
      id: '/_authed/pm/accounts/'
      path: '/accounts'
      fullPath: '/pm/accounts/'
      preLoaderRoute: typeof PmAccountsIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/hiring/settings/': {
      id: '/_authed/hiring/settings/'
      path: '/settings'
      fullPath: '/hiring/settings/'
      preLoaderRoute: typeof HiringSettingsIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/requisitions/': {
      id: '/_authed/hiring/requisitions/'
      path: '/requisitions'
      fullPath: '/hiring/requisitions/'
      preLoaderRoute: typeof HiringRequisitionsIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/hiring/candidates/': {
      id: '/_authed/hiring/candidates/'
      path: '/candidates'
      fullPath: '/hiring/candidates/'
      preLoaderRoute: typeof HiringCandidatesIndexRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/agent/workflows/': {
      id: '/_authed/agent/workflows/'
      path: '/'
      fullPath: '/agent/workflows/'
      preLoaderRoute: typeof AgentWorkflowsIndexRouteImport
      parentRoute: typeof AgentWorkflowsRouteRoute
    }
    '/_authed/pm/requests/$charterId': {
      id: '/_authed/pm/requests/$charterId'
      path: '/requests/$charterId'
      fullPath: '/pm/requests/$charterId'
      preLoaderRoute: typeof PmRequestsCharterIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/projects/$projectId': {
      id: '/_authed/pm/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/pm/projects/$projectId'
      preLoaderRoute: typeof PmProjectsProjectIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/pm/accounts/$accountId': {
      id: '/_authed/pm/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/pm/accounts/$accountId'
      preLoaderRoute: typeof PmAccountsAccountIdRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/_authed/planner/plans_/$planId': {
      id: '/_authed/planner/plans_/$planId'
      path: '/plans/$planId'
      fullPath: '/planner/plans/$planId'
      preLoaderRoute: typeof PlannerPlansPlanIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/groups_/discover': {
      id: '/_authed/planner/groups_/discover'
      path: '/groups/discover'
      fullPath: '/planner/groups/discover'
      preLoaderRoute: typeof PlannerGroupsDiscoverRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/groups_/$groupId': {
      id: '/_authed/planner/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/planner/groups/$groupId'
      preLoaderRoute: typeof PlannerGroupsGroupIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/hiring/requisitions/$requisitionId': {
      id: '/_authed/hiring/requisitions/$requisitionId'
      path: '/requisitions/$requisitionId'
      fullPath: '/hiring/requisitions/$requisitionId'
      preLoaderRoute: typeof HiringRequisitionsRequisitionIdRouteImport
      parentRoute: typeof HiringRouteRoute
    }
    '/_authed/agent/workflows/runs/$runId': {
      id: '/_authed/agent/workflows/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/agent/workflows/runs/$runId'
      preLoaderRoute: typeof AgentWorkflowsRunsRunIdRouteImport
      parentRoute: typeof AgentWorkflowsRouteRoute
    }
    '/_authed/planner/plans_/$planId_/tasks_/$taskId': {
      id: '/_authed/planner/plans_/$planId_/tasks_/$taskId'
      path: '/plans/$planId/tasks/$taskId'
      fullPath: '/planner/plans/$planId/tasks/$taskId'
      preLoaderRoute: typeof PlannerPlansPlanIdTasksTaskIdRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
    '/_authed/planner/plans_/$planId_/settings_/categories': {
      id: '/_authed/planner/plans_/$planId_/settings_/categories'
      path: '/plans/$planId/settings/categories'
      fullPath: '/planner/plans/$planId/settings/categories'
      preLoaderRoute: typeof PlannerPlansPlanIdSettingsCategoriesRouteImport
      parentRoute: typeof PlannerRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRoleAccessRoute: typeof AdminRoleAccessRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminSsoRoute: typeof AdminSsoRoute
  AdminTenantRoute: typeof AdminTenantRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminMailRoute: AdminMailRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRoleAccessRoute: AdminRoleAccessRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminSsoRoute: AdminSsoRoute,
  AdminTenantRoute: AdminTenantRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgentWorkflowsRouteRouteChildren {
  AgentWorkflowsIndexRoute: typeof AgentWorkflowsIndexRoute
  AgentWorkflowsRunsRunIdRoute: typeof AgentWorkflowsRunsRunIdRoute
}

const AgentWorkflowsRouteRouteChildren: AgentWorkflowsRouteRouteChildren = {
  AgentWorkflowsIndexRoute: AgentWorkflowsIndexRoute,
  AgentWorkflowsRunsRunIdRoute: AgentWorkflowsRunsRunIdRoute,
}

const AgentWorkflowsRouteRouteWithChildren =
  AgentWorkflowsRouteRoute._addFileChildren(AgentWorkflowsRouteRouteChildren)

interface AgentRouteRouteChildren {
  AgentWorkflowsRouteRoute: typeof AgentWorkflowsRouteRouteWithChildren
  AgentChatRoute: typeof AgentChatRoute
  AgentKnowledgeRoute: typeof AgentKnowledgeRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentWorkflowsRouteRoute: AgentWorkflowsRouteRouteWithChildren,
  AgentChatRoute: AgentChatRoute,
  AgentKnowledgeRoute: AgentKnowledgeRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

interface HiringRouteRouteChildren {
  HiringIndexRoute: typeof HiringIndexRoute
  HiringRequisitionsRequisitionIdRoute: typeof HiringRequisitionsRequisitionIdRoute
  HiringCandidatesIndexRoute: typeof HiringCandidatesIndexRoute
  HiringRequisitionsIndexRoute: typeof HiringRequisitionsIndexRoute
  HiringSettingsIndexRoute: typeof HiringSettingsIndexRoute
}

const HiringRouteRouteChildren: HiringRouteRouteChildren = {
  HiringIndexRoute: HiringIndexRoute,
  HiringRequisitionsRequisitionIdRoute: HiringRequisitionsRequisitionIdRoute,
  HiringCandidatesIndexRoute: HiringCandidatesIndexRoute,
  HiringRequisitionsIndexRoute: HiringRequisitionsIndexRoute,
  HiringSettingsIndexRoute: HiringSettingsIndexRoute,
}

const HiringRouteRouteWithChildren = HiringRouteRoute._addFileChildren(
  HiringRouteRouteChildren,
)

interface PeopleRouteRouteChildren {
  PeopleWorkerIdRoute: typeof PeopleWorkerIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteRouteChildren: PeopleRouteRouteChildren = {
  PeopleWorkerIdRoute: PeopleWorkerIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteRouteWithChildren = PeopleRouteRoute._addFileChildren(
  PeopleRouteRouteChildren,
)

interface PlannerRouteRouteChildren {
  PlannerGroupsRoute: typeof PlannerGroupsRoute
  PlannerMyTasksRoute: typeof PlannerMyTasksRoute
  PlannerTrashRoute: typeof PlannerTrashRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  PlannerGroupsGroupIdRoute: typeof PlannerGroupsGroupIdRoute
  PlannerGroupsDiscoverRoute: typeof PlannerGroupsDiscoverRoute
  PlannerPlansPlanIdRoute: typeof PlannerPlansPlanIdRoute
  PlannerPlansPlanIdSettingsCategoriesRoute: typeof PlannerPlansPlanIdSettingsCategoriesRoute
  PlannerPlansPlanIdTasksTaskIdRoute: typeof PlannerPlansPlanIdTasksTaskIdRoute
}

const PlannerRouteRouteChildren: PlannerRouteRouteChildren = {
  PlannerGroupsRoute: PlannerGroupsRoute,
  PlannerMyTasksRoute: PlannerMyTasksRoute,
  PlannerTrashRoute: PlannerTrashRoute,
  PlannerIndexRoute: PlannerIndexRoute,
  PlannerGroupsGroupIdRoute: PlannerGroupsGroupIdRoute,
  PlannerGroupsDiscoverRoute: PlannerGroupsDiscoverRoute,
  PlannerPlansPlanIdRoute: PlannerPlansPlanIdRoute,
  PlannerPlansPlanIdSettingsCategoriesRoute:
    PlannerPlansPlanIdSettingsCategoriesRoute,
  PlannerPlansPlanIdTasksTaskIdRoute: PlannerPlansPlanIdTasksTaskIdRoute,
}

const PlannerRouteRouteWithChildren = PlannerRouteRoute._addFileChildren(
  PlannerRouteRouteChildren,
)

interface PmRouteRouteChildren {
  PmIndexRoute: typeof PmIndexRoute
  PmAccountsAccountIdRoute: typeof PmAccountsAccountIdRoute
  PmProjectsProjectIdRoute: typeof PmProjectsProjectIdRoute
  PmRequestsCharterIdRoute: typeof PmRequestsCharterIdRoute
  PmAccountsIndexRoute: typeof PmAccountsIndexRoute
  PmProjectsIndexRoute: typeof PmProjectsIndexRoute
  PmRequestsIndexRoute: typeof PmRequestsIndexRoute
}

const PmRouteRouteChildren: PmRouteRouteChildren = {
  PmIndexRoute: PmIndexRoute,
  PmAccountsAccountIdRoute: PmAccountsAccountIdRoute,
  PmProjectsProjectIdRoute: PmProjectsProjectIdRoute,
  PmRequestsCharterIdRoute: PmRequestsCharterIdRoute,
  PmAccountsIndexRoute: PmAccountsIndexRoute,
  PmProjectsIndexRoute: PmProjectsIndexRoute,
  PmRequestsIndexRoute: PmRequestsIndexRoute,
}

const PmRouteRouteWithChildren =
  PmRouteRoute._addFileChildren(PmRouteRouteChildren)

interface routesAuthedRouteRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  HiringRouteRoute: typeof HiringRouteRouteWithChildren
  PeopleRouteRoute: typeof PeopleRouteRouteWithChildren
  PlannerRouteRoute: typeof PlannerRouteRouteWithChildren
  PmRouteRoute: typeof PmRouteRouteWithChildren
  routesAuthedProfileRoute: typeof routesAuthedProfileRoute
  routesAuthedIndexRoute: typeof routesAuthedIndexRoute
}

const routesAuthedRouteRouteChildren: routesAuthedRouteRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  HiringRouteRoute: HiringRouteRouteWithChildren,
  PeopleRouteRoute: PeopleRouteRouteWithChildren,
  PlannerRouteRoute: PlannerRouteRouteWithChildren,
  PmRouteRoute: PmRouteRouteWithChildren,
  routesAuthedProfileRoute: routesAuthedProfileRoute,
  routesAuthedIndexRoute: routesAuthedIndexRoute,
}

const routesAuthedRouteRouteWithChildren =
  routesAuthedRouteRoute._addFileChildren(routesAuthedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  routesAuthedRouteRoute: routesAuthedRouteRouteWithChildren,
  routes403Route: routes403Route,
  routesLoginRoute: routesLoginRoute,
  DevDatatableRoute: DevDatatableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
