import type { StatementSpec } from './inventory.ts';
import { canonicalKeys } from './manifest.ts';

const pascal = (m: string): string => m.charAt(0).toUpperCase() + m.slice(1);
const upper = (m: string): string => m.toUpperCase();

export function renderPermissionKeys(keys: readonly string[]): string {
  const union = keys.map((k) => `  | '${k}'`).join('\n');
  const arr = keys.map((k) => `  '${k}',`).join('\n');
  return `// GENERATED by pnpm gen:rbac — do not edit by hand.
export type PermissionKey =
${union};

export const ALL_PERMISSIONS: readonly PermissionKey[] = [
${arr}
];
`;
}

export function renderModuleRbac(spec: StatementSpec): string {
  const keys = canonicalKeys(spec.statement).sort();
  const slugs = spec.roles.map((r) => r.slug).sort();
  const p = pascal(spec.module);
  const u = upper(spec.module);

  const permissionType = `export type ${p}Permission =\n${keys.map((k) => `  | '${k}'`).join('\n')};`;
  const permissionsConst = `export const ${u}_PERMISSIONS: readonly ${p}Permission[] = [\n${keys.map((k) => `  '${k}',`).join('\n')}\n];`;
  const roleSlugsConst = `export const ${u}_ROLE_SLUGS = [\n${slugs.map((s) => `  '${s}',`).join('\n')}\n] as const;`;

  return `// GENERATED by pnpm gen:rbac — do not edit by hand.
${permissionType}

${permissionsConst}

${roleSlugsConst}
`;
}
