-- drizzle cannot model: extensions, RANGE partitioning, constraint triggers, views, RLS policies, grants

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Partitioned event bus / audit log. drizzle pgTable cannot express PARTITION BY RANGE,
-- deferred constraint triggers, or pg_notify wiring. The typed schema lives in
-- src/db/schema/events.ts for read/write access. Trace columns (W3C trace context,
-- RFC 9110 traceparent/tracestate) are folded into the canonical CREATE TABLE below.
CREATE TABLE core.events (
  id                 uuid        NOT NULL,
  occurred_at        timestamptz NOT NULL DEFAULT now(),
  tenant_id          uuid        NOT NULL,
  aggregate_type     text        NOT NULL,
  aggregate_id       text        NOT NULL,
  event_type         text        NOT NULL,
  event_version      int         NOT NULL,
  payload            jsonb       NOT NULL,
  caused_by_user_id  uuid,
  caused_by_event_id uuid,
  trace_id           text,
  trace_parent       text,
  trace_state        text,
  actor              jsonb,
  before             jsonb,
  after              jsonb,
  PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE INDEX events_aggregate_idx ON core.events (aggregate_type, aggregate_id, occurred_at);
CREATE INDEX events_type_idx      ON core.events (event_type, event_version, occurred_at);
CREATE INDEX events_tenant_idx    ON core.events (tenant_id, occurred_at);
CREATE INDEX events_occurred_brin ON core.events USING brin (occurred_at);

CREATE OR REPLACE FUNCTION core.ensure_events_partition(month_start date) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
  part_name  text := format('events_y%sm%s', to_char(month_start, 'YYYY'), to_char(month_start, 'MM'));
  next_month date := (month_start + interval '1 month')::date;
BEGIN
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS core.%I PARTITION OF core.events FOR VALUES FROM (%L) TO (%L)',
    part_name, month_start, next_month
  );
END $$;

SELECT core.ensure_events_partition((date_trunc('month', now()) + (n || ' months')::interval)::date)
FROM generate_series(0, 12) AS n;

CREATE OR REPLACE FUNCTION core._notify_events() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN PERFORM pg_notify('events', ''); RETURN NULL; END $$;

CREATE CONSTRAINT TRIGGER events_notify
  AFTER INSERT ON core.events
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION core._notify_events();

-- Audit projection over the event bus (final definition from old 0005_audit_v_with_aggregate).
CREATE VIEW core.audit_v AS
  SELECT
    id AS event_id,
    occurred_at,
    tenant_id,
    event_type,
    aggregate_type,
    aggregate_id,
    actor,
    payload,
    before,
    after,
    trace_id
  FROM core.events
  WHERE actor IS NOT NULL;

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION core.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER skill_touch_updated_at
BEFORE UPDATE ON core.skill
FOR EACH ROW EXECUTE FUNCTION core.tg_touch_updated_at();
CREATE TRIGGER skill_category_touch_updated_at
BEFORE UPDATE ON core.skill_category
FOR EACH ROW EXECUTE FUNCTION core.tg_touch_updated_at();
CREATE TRIGGER subscription_failure_state_touch_updated_at
BEFORE UPDATE ON core.subscription_failure_state
FOR EACH ROW EXECUTE FUNCTION core.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE core.skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.skill FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON core.skill
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE core.skill_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.skill_category FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON core.skill_category
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE core.session_scope_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.session_scope_cache FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON core.session_scope_cache
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA core TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
