// Dev-only. Run: pnpm exec tsx packages/knowledge/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_knowledge_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'knowledge';

// files is the only table with updated_at. chunks is append-only (created_at only).
const TOUCH_TABLES = ['files'];

// Both tenant-scoped tables get the RLS backstop policy. chunks is the LIST-partitioned
// parent; policies on it are inherited by the per-tenant child partitions.
const RLS_TABLES = ['files', 'chunks'];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
