-- drizzle cannot model: touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ./generate-platform-sql.ts.

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION integrations.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER m365_group_links_touch_updated_at
BEFORE UPDATE ON integrations.m365_group_links
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();
CREATE TRIGGER m365_subscriptions_touch_updated_at
BEFORE UPDATE ON integrations.m365_subscriptions
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();
CREATE TRIGGER m365_plan_links_touch_updated_at
BEFORE UPDATE ON integrations.m365_plan_links
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();
CREATE TRIGGER m365_resource_etags_touch_updated_at
BEFORE UPDATE ON integrations.m365_resource_etags
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();
CREATE TRIGGER m365_tenant_config_touch_updated_at
BEFORE UPDATE ON integrations.m365_tenant_config
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();
CREATE TRIGGER mail_transport_config_touch_updated_at
BEFORE UPDATE ON integrations.mail_transport_config
FOR EACH ROW EXECUTE FUNCTION integrations.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE integrations.m365_group_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.m365_group_links FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.m365_group_links
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE integrations.m365_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.m365_subscriptions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.m365_subscriptions
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE integrations.m365_plan_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.m365_plan_links FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.m365_plan_links
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE integrations.m365_resource_etags ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.m365_resource_etags FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.m365_resource_etags
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE integrations.m365_tenant_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.m365_tenant_config FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.m365_tenant_config
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE integrations.mail_transport_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations.mail_transport_config FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON integrations.mail_transport_config
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA integrations TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA integrations TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA integrations GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
