// Dev-only. Run: pnpm exec tsx packages/integrations/drizzle/migrations/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_integrations_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'integrations';

// Every integrations table carries updated_at and is mutated in place by the sync engine.
const TOUCH_TABLES = [
  'm365_group_links',
  'm365_subscriptions',
  'm365_plan_links',
  'm365_resource_etags',
  'm365_tenant_config',
  'mail_transport_config',
  // M365/Entra directory sync (FUT-842 Task 2).
  'm365_person_links',
  'm365_org_unit_links',
  'm365_directory_conflict',
];

// Every integrations table is tenant-scoped (all carry tenant_id) and gets the RLS backstop
// policy (constitution: none allowlisted).
const RLS_TABLES = [
  'm365_group_links',
  'm365_subscriptions',
  'm365_plan_links',
  'm365_resource_etags',
  'm365_tenant_config',
  'mail_transport_config',
  // M365/Entra directory sync (FUT-842 Task 2).
  'm365_person_links',
  'm365_org_unit_links',
  'm365_directory_conflict',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
