-- drizzle cannot model: extensions, touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ./generate-platform-sql.ts.

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS vector;

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION identity.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER access_group_touch_updated_at
BEFORE UPDATE ON identity.access_group
FOR EACH ROW EXECUTE FUNCTION identity.tg_touch_updated_at();
CREATE TRIGGER org_unit_projection_touch_updated_at
BEFORE UPDATE ON identity.org_unit_projection
FOR EACH ROW EXECUTE FUNCTION identity.tg_touch_updated_at();
CREATE TRIGGER person_projection_touch_updated_at
BEFORE UPDATE ON identity.person_projection
FOR EACH ROW EXECUTE FUNCTION identity.tg_touch_updated_at();
CREATE TRIGGER role_permission_overlays_touch_updated_at
BEFORE UPDATE ON identity.role_permission_overlays
FOR EACH ROW EXECUTE FUNCTION identity.tg_touch_updated_at();
CREATE TRIGGER tenant_sso_providers_touch_updated_at
BEFORE UPDATE ON identity.tenant_sso_providers
FOR EACH ROW EXECUTE FUNCTION identity.tg_touch_updated_at();

-- identity.user is EXEMPT from RLS: its only non-admin reader is better-auth's pre-tenant
-- email lookup at login (getPool('web'), no tenant GUC set); the identity domain layer reads
-- user via getPool('worker') (admin, bypasses RLS). session/account/verification/rate_limit/
-- failed_login_* are non-tenant auth-runtime tables and stay non-RLS as well.
-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE identity.access_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.access_group FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.access_group
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.access_group_membership ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.access_group_membership FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.access_group_membership
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.access_group_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.access_group_role FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.access_group_role
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.role_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.role_assignments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.role_assignments
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.role_permission_overlays ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.role_permission_overlays FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.role_permission_overlays
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.product_grant ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.product_grant FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.product_grant
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.person_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.person_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.person_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.org_unit_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.org_unit_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.org_unit_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE identity.tenant_sso_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.tenant_sso_providers FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON identity.tenant_sso_providers
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA identity TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
