// Dev-only. Run: pnpm exec tsx packages/identity/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_identity_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'identity';

// Identity-OWNED tables with an updated_at column. better-auth-managed user/session/account/
// verification are intentionally excluded: better-auth's adapter owns their timestamps.
const TOUCH_TABLES = [
  'access_group',
  'org_unit_projection',
  'person_projection',
  'role_permission_overlays',
  'tenant_sso_providers',
];

// Tenant-scoped tables that get the RLS backstop policy (spec §3.1). identity.user is exempt:
// its only non-admin reader is better-auth's pre-tenant email lookup, which cannot set the
// tenant GUC at login. The identity domain layer reads user via the admin pool (bypasses RLS).
const RLS_TABLES = [
  'access_group',
  'access_group_membership',
  'access_group_role',
  'role_assignments',
  'role_permission_overlays',
  'product_grant',
  'person_projection',
  'org_unit_projection',
  'tenant_sso_providers',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
