// Dev-only. Run: pnpm exec tsx packages/pm/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_pm_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'pm';

// Every pm table carries an updated_at column that must be bumped on every UPDATE.
// kpi_applied_metric is excluded: it has no updated_at (toggling applied metrics is
// insert/delete, never an in-place edit).
const TOUCH_TABLES = [
  'account',
  'project',
  'project_approval',
  'account_recruiter',
  'allocation',
  'project_access',
  'person_projection',
  'staffing_plan_line',
  'staffing_plan_line_skill',
  'kpi_norm',
  'kpi_norm_metric',
  'kpi_record',
  'kpi_record_entry',
  // Weekly Report & KPI Performance (FUT-609) — mutable tables only.
  // flag_audit_entry and norm_snapshot are immutable (no updated_at) and excluded.
  'report',
  'metric_value',
  'flag',
  'project_week_rollup',
  'comment',
];

// Every pm table is tenant-scoped and gets the RLS backstop policy (constitution: none
// allowlisted). Includes the person_projection cross-module read model.
const RLS_TABLES = [
  'account',
  'project',
  'project_approval',
  'account_recruiter',
  'allocation',
  'project_access',
  'person_projection',
  'staffing_plan_line',
  'staffing_plan_line_skill',
  'kpi_norm',
  'kpi_norm_metric',
  'kpi_applied_metric',
  'kpi_record',
  'kpi_record_entry',
  // Weekly Report & KPI Performance (FUT-609) — all seven tables are tenant-scoped.
  'report',
  'metric_value',
  'flag',
  'flag_audit_entry',
  'norm_snapshot',
  'project_week_rollup',
  'comment',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
