-- drizzle cannot model: touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ../generate-platform-sql.ts.

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION pm.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER account_touch_updated_at
BEFORE UPDATE ON pm.account
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER project_touch_updated_at
BEFORE UPDATE ON pm.project
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER account_recruiter_touch_updated_at
BEFORE UPDATE ON pm.account_recruiter
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER allocation_touch_updated_at
BEFORE UPDATE ON pm.allocation
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER charter_touch_updated_at
BEFORE UPDATE ON pm.charter
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER project_access_touch_updated_at
BEFORE UPDATE ON pm.project_access
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER worker_projection_touch_updated_at
BEFORE UPDATE ON pm.worker_projection
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER staffing_plan_line_touch_updated_at
BEFORE UPDATE ON pm.staffing_plan_line
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();
CREATE TRIGGER staffing_plan_line_skill_touch_updated_at
BEFORE UPDATE ON pm.staffing_plan_line_skill
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE pm.account ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.account FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.account
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.project ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.project FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.project
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.account_recruiter ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.account_recruiter FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.account_recruiter
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.allocation ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.allocation FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.allocation
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.charter ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.charter FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.charter
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.project_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.project_access FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.project_access
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.worker_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.worker_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.worker_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.staffing_plan_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.staffing_plan_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.staffing_plan_line
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE pm.staffing_plan_line_skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.staffing_plan_line_skill FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.staffing_plan_line_skill
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA pm TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pm TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
