-- RLS policy + touch trigger: drizzle-kit cannot model these; generated by generate-platform-sql.ts
CREATE TRIGGER project_approval_touch_updated_at
BEFORE UPDATE ON pm.project_approval
FOR EACH ROW EXECUTE FUNCTION pm.tg_touch_updated_at();

ALTER TABLE pm.project_approval ENABLE ROW LEVEL SECURITY;
ALTER TABLE pm.project_approval FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pm.project_approval
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
