// Dev-only. Run: pnpm exec tsx packages/people/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_people_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'people';

// Tables with an updated_at column that must be bumped on every UPDATE. person_history is a
// append-only audit log (timestamped by `at`, no updated_at) and is intentionally excluded.
const TOUCH_TABLES = [
  'person',
  'employment_period',
  'org_unit',
  'person_skill',
  'worker_allocation_projection',
  'account_projection',
  'project_projection',
  'user_projection',
];

// Every people table is tenant-scoped and gets the RLS backstop policy (constitution: none
// allowlisted). Includes the four cross-module read-model projections.
const RLS_TABLES = [
  'person',
  'employment_period',
  'org_unit',
  'person_skill',
  'person_history',
  'worker_allocation_projection',
  'account_projection',
  'project_projection',
  'user_projection',
  'performance_evaluation_group',
  'performance_config_revision',
  'performance_config_month_pin',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
