-- drizzle cannot model: generated tsvector columns, GIN on them, touch triggers, RLS policies, grants.
-- Sections (touch triggers, RLS) are the verbatim output of ./generate-platform-sql.ts.

-- Full-text search column + GIN index on planner.tasks (verbatim from the pre-squash 0006).
ALTER TABLE planner.tasks
  ADD COLUMN search_tsv tsvector
    GENERATED ALWAYS AS (
      setweight(to_tsvector('english', coalesce(title, '')),       'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B')
    ) STORED;

CREATE INDEX tasks_search_tsv_gin_idx
  ON planner.tasks USING gin (search_tsv);

-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql
CREATE OR REPLACE FUNCTION planner.tg_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
CREATE TRIGGER groups_touch_updated_at
BEFORE UPDATE ON planner.groups
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER plans_touch_updated_at
BEFORE UPDATE ON planner.plans
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER plan_categories_touch_updated_at
BEFORE UPDATE ON planner.plan_categories
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER buckets_touch_updated_at
BEFORE UPDATE ON planner.buckets
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER tasks_touch_updated_at
BEFORE UPDATE ON planner.tasks
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER checklist_items_touch_updated_at
BEFORE UPDATE ON planner.checklist_items
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER labels_touch_updated_at
BEFORE UPDATE ON planner.labels
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER task_references_touch_updated_at
BEFORE UPDATE ON planner.task_references
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER task_comments_touch_updated_at
BEFORE UPDATE ON planner.task_comments
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();
CREATE TRIGGER group_join_requests_touch_updated_at
BEFORE UPDATE ON planner.group_join_requests
FOR EACH ROW EXECUTE FUNCTION planner.tg_touch_updated_at();

-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)
ALTER TABLE planner.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.groups FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.groups
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.group_members FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.group_members
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.plans FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.plans
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.plan_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.plan_categories FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.plan_categories
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.buckets ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.buckets FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.buckets
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.tasks
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.task_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.task_assignments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.task_assignments
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.checklist_items FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.checklist_items
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.labels FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.labels
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.task_labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.task_labels FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.task_labels
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.task_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.task_references FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.task_references
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.task_comments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.task_comments
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.group_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.group_join_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.group_join_requests
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE planner.assignee_projection ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.assignee_projection FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.assignee_projection
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Grants for the least-privilege app role. Guarded so self-host without the role still migrates.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'seta_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA planner TO seta_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA planner TO seta_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA planner GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seta_app';
  END IF;
END $$;
