-- drizzle cannot model: row-level security policies.
--
-- Every planner table is tenant-scoped and gets the RLS backstop policy — the
-- constitution allowlists none, and `tests/integration/rls-census.test.ts`
-- enforces it for every table in the schema. `task_links` arrived in 0003, so it
-- needs the same treatment the other 14 tables got in 0001_planner_platform.sql.
--
-- Generated by @seta/shared-db buildRlsSql('planner', ['task_links']); the table
-- is also listed in drizzle/generate-platform-sql.ts so a regenerate reproduces
-- it. Backstop only — the app still writes an explicit WHERE tenant_id.
ALTER TABLE planner.task_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner.task_links FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON planner.task_links
  USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
