// Dev-only. Run: pnpm exec tsx packages/planner/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_planner_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'planner';

// Tables with an updated_at column that must be bumped on every UPDATE. group_members,
// task_assignments, task_labels (join tables, timestamped by *_at) and assignee_projection
// (projection, projection_built_at) have no updated_at and are excluded.
const TOUCH_TABLES = [
  'groups',
  'plans',
  'plan_categories',
  'buckets',
  'tasks',
  'checklist_items',
  'labels',
  'task_references',
  'task_comments',
  'group_join_requests',
];

// Every planner table is tenant-scoped and gets the RLS backstop policy (constitution: none
// allowlisted). Includes the join tables and assignee_projection read-model.
const RLS_TABLES = [
  'groups',
  'group_members',
  'plans',
  'plan_categories',
  'buckets',
  'tasks',
  'task_assignments',
  'checklist_items',
  'labels',
  'task_labels',
  'task_references',
  'task_comments',
  'group_join_requests',
  'assignee_projection',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
