// Dev-only. Run: pnpm exec tsx packages/notifications/drizzle/migrations/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_notifications_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'notifications';

// Only notification_prefs is mutated in place (updated_at). The notifications feed is
// insert-then-mark-read (read_at/dismissed_at), timestamped by created_at — no updated_at.
const TOUCH_TABLES = ['notification_prefs'];

// Both notifications tables are tenant-scoped (carry tenant_id) and get the RLS backstop
// policy (constitution: none allowlisted).
const RLS_TABLES = ['notification_prefs', 'notifications'];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
