// Dev-only. Run: pnpm exec tsx packages/hiring/drizzle/generate-platform-sql.ts
// Prints the touch-trigger and RLS sections of 0001_hiring_platform.sql from the PR0
// @seta/shared-db builders so those sections are provably generated, not hand-typed.
import { buildRlsSql, buildTouchTriggerSql, buildTouchUpdatedAtFnSql } from '@seta/shared-db';

const SCHEMA = 'hiring';

// Tables with an updated_at column that must be bumped on every UPDATE. candidate_event is an
// append-only activity feed (timestamped by created_at, no updated_at) and is excluded.
const TOUCH_TABLES = [
  'requisition',
  'opening',
  'requisition_jd_section',
  'requisition_skill',
  'opening_close_reason',
  'jd_template',
  'jd_template_section',
  'candidate',
  'candidate_skill',
  'rejection_reason',
  'application',
];

// Every hiring table is tenant-scoped and gets the RLS backstop policy (constitution: none
// allowlisted). Includes candidate_event (append-only, no updated_at, still tenant-scoped).
// account_projection/project_projection/worker_user_projection (FUT-326/327) and
// project_owner_projection (FUT-328) are local read-models fed by other modules' events —
// still tenant-scoped, no updated_at column.
const RLS_TABLES = [
  'requisition',
  'opening',
  'requisition_jd_section',
  'requisition_skill',
  'opening_close_reason',
  'jd_template',
  'jd_template_section',
  'candidate',
  'candidate_skill',
  'rejection_reason',
  'candidate_event',
  'application',
  'account_projection',
  'project_projection',
  'worker_user_projection',
  'project_owner_projection',
];

const lines: string[] = [];

lines.push(
  '-- touch-updated-at: generated by @seta/shared-db buildTouchUpdatedAtFnSql/buildTouchTriggerSql',
);
lines.push(buildTouchUpdatedAtFnSql(SCHEMA));
for (const table of TOUCH_TABLES) {
  lines.push(buildTouchTriggerSql(SCHEMA, table));
}
lines.push('');
lines.push(
  '-- rls: generated by @seta/shared-db buildRlsSql (backstop; app still writes explicit WHERE tenant_id)',
);
lines.push(buildRlsSql(SCHEMA, RLS_TABLES));

process.stdout.write(`${lines.join('\n')}\n`);
